### ISSUE TITLE
[BUG] Box fails for R_BUBBLE_MAX > BOX_LEN

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#112]
We should issue a warning when either `R_BUBBLE_MAX > BOX_LEN` or `HII_FILTER_RADIUS = 1` and `R_BUBBLE_MAX <= BOX_LEN/3`.

**Comment by steven-murray** [comment]
Raising an error would be better -- it's definitely nonsense output.

**Comment by andreimesinger** [comment]
why not just force it to be less than box_len?

**Comment by steven-murray** [comment]
Raising an error will essentially do just that. I think "automatically" setting parameters silently (eg. doing `R_BUBBLE_MAX = min(R_BUBBLE_MAX, BOX_LEN)`) is more obfuscated for the user. That's OK if it's a _default_, but we don't want to silently change user input. Easier just to raise a useful error and let the user change it themselves.

**Comment by steven-murray** [comment]
Maybe we just set the parameter to be reasonable, but also warn the user.
