### ISSUE TITLE
Tk should be volume weighted temperature between HI and HII

### ISSUE THREAD

**Issue by qyx268** [21cmfast/21cmFAST#120]
**Is your feature request related to a problem? Please describe.**

Currently, Tk_box in spin_temp represents the kinetic temperature of the IGM for its neutral part only. In principle, it should be the volume-weighted temperature between HI and HII.

**Describe the solution you'd like**

Because we still need previous_spin_temp->Tk in SpinTemperatureBox.c, we cannot simply alter spin_temp->Tk_box inside IonisationBox.c, where we can have the required ionization history. Therefore, in branch `better_Tk`, I had to add a new box, TkIGM_box, in IonizedBox to store the real volume-weighted IGM Tk. 

This plot shows the difference, running with flag_options = {"INHOMO_RECO":True, 'USE_MASS_DEPENDENT_ZETA':False, 'USE_TS_FLUCT':True, 'USE_MINI_HALOS':False}, HII_DIM = 128 and BOX_LEN = 250.
LC (Ts, Tk and TkIGM have the same color scheme):
![image](https://user-images.githubusercontent.com/15994713/76811986-bd5e2900-67f3-11ea-8d52-4785044a7cd9.png)
mean:
![image](https://user-images.githubusercontent.com/15994713/76811989-c222dd00-67f3-11ea-8b00-62629e30faef.png)

I think this result, in general, makes sense. We see at high z, TkIGM basically follows Tk except for those ionized regions where TkIGM is either xHI * Tk + (1-xHI) * 1e4 in the case of partial ionization or equation 6 from McQuinn 2015 for fully ionized regions.
![image](https://user-images.githubusercontent.com/15994713/76811320-65262780-67f1-11ea-97dc-4e7c2a002400.png)
We also see the HII regions cool down after firstly getting ionized. I'm not sure if the temperature of those partially ionized regions is okay or not though. You see these weird jumps in the global evolution (although it's pretty smooth if plotting in linear scale). Note that at these redshifts, Tk is only 10K in HI region and thus HII filling factor of ~0.1% will raise the volume-weighted Tk to be twice the HI region... 

**Describe alternatives you've considered**

**Additional context**

At least, for the sake of saving storage, we might want to not output spin_temp->Tk.

Also, since I've added Fcoll and Fcoll_MINI, which are usually unnecessary to output and can be very storage-consuming if USE_MINI_HALOS. Can we also, by default, not output them? I'm not sure whether not outputting everything will affect caching or not...

**Comment by andreimesinger** [comment]
hmm....  is this run with the stochastic halo abundances on?  i.e. N_Poisson is set to something positive?

after looking at this, i think we might skip the Tk adjustment for partially ionized cells, o r at least not do them so early in the EoR...   i will think on it tomorrow..

**Comment by qyx268** [comment]
I believe it is with n_poisson=5

**Comment by steven-murray** [comment]
Concerning the outputs: we should try to be conservative. If I'm not mistaken, the `MINI_HALO` outputs are already conditional -- they are initialised to zero-length arrays if `MINI_HALOS` is not being used. 

Obviously any box that is being used down the line needs to be produced and written to the cache. At the moment we have no mechanism for "optional" outputs, i.e. things that the user might want to get and plot, but aren't necessary for further calculations. We could think about implementing that, though I think that's a v4 kind of upgrade -- it has a lot of subtleties, like what happens if a box in cache is run with the same parameters, but has saved an extra output? Is it considered equivalent and therefore useable? Probably that is fine, but then what if we realize that there is an extra feature we want down the line that requires that extra output? It then becomes non-optional. How do we manage that? So it opens up a can of worms, which we should be careful about figuring out before we dive headlong into it.

I hope I'm addressing your concern :-)

**Comment by qyx268** [comment]
thx @steven-murray, I understand it. Actually, it also happened to me that after I finished a LC run, I manually deleted IonizedBox_* and tried to rerun the same LC using the cached TsBox_* and BrightnessTemp_* because I only changed the calculation of IonizedBox_*. It crashed, which made me wonder the caching might not be very flexible and can be difficult to implement like what you described.

We can for sure postpone this to future work. It's not urgent.

**Comment by qyx268** [comment]
Sorry, there was a bug in the calculation for fully ionized cells which ends up having too low temperature for those cells. Apparently the issue was not in the partially ionized cells. I rerun it after fixing it. Note that I re-run with USE_MASS_DEPENDENT_ZETA=True this time.
flag_options_fid = {"INHOMO_RECO":True, 'USE_MASS_DEPENDENT_ZETA':True, 'USE_TS_FLUCT':True, 'USE_MINI_HALOS':False}

LC:
![image](https://user-images.githubusercontent.com/15994713/76885895-415df280-6880-11ea-955e-673572295681.png)

mean read from the lightcone class (1st row) 
mean of the lightcone shown above (2nd row)
median of the lightcone shown above (3rd row)
and 15 random sightlines:
![image](https://user-images.githubusercontent.com/15994713/76890444-ae28bb00-6887-11ea-97e6-fa35707186c7.png)

Firstly, I think the difference between the mean read from the lightcone class and the mean from postprocessing, e.g. np.mean(lightcone.TkIGM_box,axis=(0,1)) is because the former is calculated using the co-evolve boxes while the later is done from the LC which is produced by glueing pieces from co-evolve boxes.

Secondly, I think the huge dispersion of TkIGM resulting in very different mean and median evolution. I'm worried if we can actually use LC to study individual sightlines... 

Nevertheless, you can see from each sightline (e.g. the upper envelope), that the HII gets heated to very high temperatures (e.g. 1e7K) and then cools down gradually. Although you cannot see it in the mean, the median sort of shows that -- basically at the end of EoR, the gas gets heated to 1e5 and then starts to cool.

I suspect the high temperature is due to the density term in the McQuinn equation. Since I assume Ti = 1e4, the first term (from a passing ionization front) does not contribute significantly compared to the second term (photonheating equilibrium).

**Comment by qyx268** [comment]
actually, I wasn't using the correct density apparently.. have to update this again.

**Comment by andreimesinger** [comment]
ok, when you do, it would be useful to include a plot of the temperature vs redshift of a couple of cells, to make sure things look reasonable

**Comment by qyx268** [comment]
okay, the density bug is not a huge impact. The results look quite similar with the value, in general, being slightly smaller. However, I just realized that we don't inherit z_re from the previous box and therefore I was passing z_re=0 to the temperature calculation. Now the result looks much better. Here is the evolution of some randomly picked cells. I've changed the last column to \Delta

![image](https://user-images.githubusercontent.com/15994713/76904471-58acd800-68a0-11ea-85c6-3f06b4c34d4e.png)
![image](https://user-images.githubusercontent.com/15994713/76911875-463b9a00-68b2-11ea-962a-e50981409a56.png)

I think it looks okay. You see the evolution of the temperature basically follows xH: T reaches around 1e4K when xH~0. The earlier xH reaches 0, the higher T becomes due to the (1+z) turn in T_0,lim term. Before xH reaches 0, T is volume-weighted between 1e4 and HI temperature. After xH reaches 0, T starts to decreases as the gas cools down.

**Comment by qyx268** [comment]
We've decided to not do partial reionization since we don't know how the Q factor works in these areas. I've removed them accordingly. Results are rerun with HII_DIM = 200 DIM=800 and BOX_LEN = 250 to have higher density resolution for forest calculation...

![image](https://user-images.githubusercontent.com/15994713/77017284-5919a180-697a-11ea-88c5-19871d84c158.png)

![image](https://user-images.githubusercontent.com/15994713/77017362-9ed66a00-697a-11ea-93e4-59413a6e02c2.png)

I think we might want to do partial reionization for those ionized cells which have recombined to remove those sudden drops when xH becomes higher (which rarely happens unless the density suddenly increases a lot... ) 

You can notice that z_re_box no longer has any stripes. It turns out that they were happening because we do not inherit z_re from the previous box. I've added LC of z_re back to the calculation accordingly (#119)

**Comment by qyx268** [comment]
closed by #121
