### ISSUE TITLE
Installation errors in Ubuntu 18.04 and CentOS 7

### ISSUE THREAD

**Issue by parphyam** [21cmfast/21cmFAST#128]
Hello ,
I am trying to install the software in my Ubuntu machine. On doing 
`pip install git+git://github.com/21cmFAST/21cmFAST.git`,  a very large error message is being generated that I am attaching in the text file. 
[error.txt](https://github.com/21cmfast/21cmFAST/files/4439066/error.txt)

I have a previous version installed in another CentOS 7 machine. The same error message is being generated there as well.

**Comment by steven-murray** [comment]
Hi @parphyam , the error seems to be either that you don't have FFTW3 installed, or that you are not pointing to it correctly. Have you done `sudo apt-get install libfftw3-dev`? If so, can you find the path to the library files installed by this package?

**Comment by parphyam** [comment]
On doing `ldconfig -p | grep libfftw` I am getting the following output :

`libfftw3l_threads.so.3 (libc6,x86-64) => /lib64/libfftw3l_threads.so.3
	libfftw3l_threads.so (libc6,x86-64) => /lib64/libfftw3l_threads.so
	libfftw3l_omp.so.3 (libc6,x86-64) => /lib64/libfftw3l_omp.so.3
	libfftw3l_omp.so (libc6,x86-64) => /lib64/libfftw3l_omp.so
	libfftw3l.so.3 (libc6,x86-64) => /lib64/libfftw3l.so.3
	libfftw3l.so (libc6,x86-64) => /lib64/libfftw3l.so
	libfftw3f_threads.so.3 (libc6,x86-64) => /lib64/libfftw3f_threads.so.3
	libfftw3f_threads.so (libc6,x86-64) => /lib64/libfftw3f_threads.so
	libfftw3f_omp.so.3 (libc6,x86-64) => /lib64/libfftw3f_omp.so.3
	libfftw3f_omp.so (libc6,x86-64) => /lib64/libfftw3f_omp.so
	libfftw3f.so.3 (libc6,x86-64) => /lib64/libfftw3f.so.3
	libfftw3f.so (libc6,x86-64) => /lib64/libfftw3f.so
	libfftw3_threads.so.3 (libc6,x86-64) => /lib64/libfftw3_threads.so.3
	libfftw3_threads.so (libc6,x86-64) => /lib64/libfftw3_threads.so
	libfftw3_omp.so.3 (libc6,x86-64) => /lib64/libfftw3_omp.so.3
	libfftw3_omp.so (libc6,x86-64) => /lib64/libfftw3_omp.so
	libfftw3.so.3 (libc6,x86-64) => /lib64/libfftw3.so.3
	libfftw3.so (libc6,x86-64) => /lib64/libfftw3.so `
So the libraries are installed. Do I need to explicitly mention the LD_LIBRARY_PATH, even though the installation location seems standard?

**Comment by steven-murray** [comment]
Can you try installing by doing `LIB=/lib64 INC=<path to directory
containing fftw headers> pip install git+git://
github.com/21cmFAST/21cmFAST.git`? If your GSL installation is in a
different location, you can point to each separately by using `FFTW_LIB`
and `GSL_LIB` and likewise for `INC`. I'm not sure what is considered
"standard" on different systems -- /lib64 may or may not be considered a
standard place to search for libraries.

**Comment by parphyam** [comment]
Hi, 
I tried doing `LIB=/lib64 INC=/usr/include  pip install git+git://github.com/21cmFAST/21cmFAST.git` and got `ERROR: Command errored out with exit status 128: git clone -q git://github.com/21cmFAST/21cmFAST.git /tmp/pip-req-build-V0f15j Check the logs for full command output`

**Comment by steven-murray** [comment]
Hmmm, I don't know what that error is, but it most certainly is not to do with `21cmFAST` itself. It seems like an error to do with git configuration or perhaps permissions. Can you do a simple `git clone git@github.com:21cmFAST/21cmFAST`? If so, you can install by entering that directory and doing `LIB=/lib64 INC=/usr/include pip install .`

**Comment by parphyam** [comment]
Hi, 
On doing `git clone https://github.com/21cmfast/21cmFAST ` followed by `LIB=/lib64 INC=/usr/include pip install .`, the software installed correctly and is running. Thank you for the help. 
Also, thank you for the detailed documentation. I didn't find anything on the 'API Reference' Page, so I guess it is still under development. I have a request in terms of the documentation. If it possible could you kindly put the details of the 'AstroParams', 'UserParams' etc in the documentation? Doing `p21c.AstroParams._defaults_` returns 
`{'HII_EFF_FACTOR': 30.0,
 'F_STAR10': -1.3,
....
....
}` 
which is not very clear. 
Thank you again for your help.

**Comment by steven-murray** [comment]
Great, glad that it worked! Thanks for pointing out the failure of the documentation to compile... the details of `AstroParams` etc. should be under that API Reference page, so you can check there in the future once I've fixed the docs. In the meantime, the same docs can be accessed in an interactive session using eg. `AstroParams?`

**Comment by aishrimc** [comment]
Hello, I am having the same error mentioned in this comment (the last line of the very large error message reads `ERROR: Could not build wheels for 21cmFAST which use PEP 517 and cannot be installed directly`). I have anaconda3 installed and used the command 
` LIB=/home/aa/anaconda3/lib INC=/home/aa/anaconda3/include pip install .` inside the 21cmFAST directory obtained by doing `git clone https://github.com/21cmfast/21cmFAST`.  The machine is running in Ubuntu 16.04.6 LTS. 
In a laptop with 8 GB ram (Ubuntu 18.04.4 LTS), the installation was fine with anaconda3 and the examples simulations given in the documentation also ran. However, the program gets killed when trying to run a lightcone simulation.

**Comment by steven-murray** [comment]
Hi @aishrimc -- can you give the full error output? Did you install both `gsl` and `fftw` using the `conda-forge` channel?

Building a lightcone with default parameters probably does take more than 8GB RAM -- default parameters are `HII_DIM=200`, which results in quite large initial conditions. If you set `HII_DIM=100`, does it finish the computation?

**Comment by aishrimc** [comment]
The full output is in the attached text file. 
[inst-err.txt](https://github.com/21cmfast/21cmFAST/files/4622962/inst-err.txt)
Both gsl and fftw were installed via the  `conda-forge`  channel.

**Comment by steven-murray** [comment]
That is very strange. It looks like all the errors you're getting have to do with complex numbers -- we include `complex.h`, but it looks like that's somehow not being picked up?

**Comment by steven-murray** [comment]
Hi @aishrimc have you gotten any further with this issue?

**Comment by steven-murray** [comment]
Closing for now as no response, but feel free to reopen.

**Comment by aishrimc** [comment]
Hi,
Sure, please close the issue. I couldn't figure out the problem; maybe
there was some issue in the basic gcc installation, since I managed to
install it in another machine.
