### ISSUE TITLE
[BUG] Incorrect LFs when not using mini haloes

### ISSUE THREAD

**Issue by BradGreig** [21cmfast/21cmFAST#130]
**Describe the bug:**
When `USE_MINI_HALOS = False` the LFs are incorrectly generated as the `M_TURNS` have not been correctly cast as floats from python precision. The mturnovers array must be cast to float 32 precision under this condition.

Also note, `astro_params.M_TURN` contains the exponent to the log10, thus, the values for `mturnovers` must also be converted to 10**(astro_params.M_TURN)

At the same time, it would be useful to add tests to the LFs to avoid issues like this occurring.

**Comment by qyx268** [comment]
yeah, I'm still working on this through #115. Thanks for the notes

**Comment by steven-murray** [comment]
Closing in favour of #115
