### ISSUE TITLE
[Feature Req.] Specify redshift outputs for run_lightcone

### ISSUE THREAD

**Issue by plaplant** [21cmfast/21cmFAST#137]
**Is your feature request related to a problem? Please describe.**

When using the `run_lightcone` function, it seems like the output redshifts for the lightcone are determined based on the values of `redshift`, `max_redshift`, and `ZPRIME_STEP_FACTOR`. It would be nice to also have the option to exactly specify the redshift values desired. This would provide flexibility when comparing against snapshots from other semi-numeric calculations, or target redshifts for upcoming experiments.

**Describe the solution you'd like**

The `run_lightcone` function should take an optional argument where the user specifies the redshift values to use when constructing the lightcone.

**Describe alternatives you've considered**

I think this would replace the values returned by the `_logscroll_redshifts` function, though I'm not sure if there are other changes that would need to be made.

**Comment by BradGreig** [comment]
Hi @plaplant, yes, this should be able to be added.

In the meantime, one could do something similar to this already with the `run_coeval` function (which you may already know). This function allows the user to specify whatever redshift they want a co_eval box to be returned at. Now, the base 21-cm evolution will still be performed using the same lowest redshift, `max_redshift` and `ZPRIME_STEP_FACTOR` combination but then the additional user defined redshifts will be inserted into the list to provide the additional co_eval boxes at those specified redshifts. This may be of use in the meantime before this feature request can be addressed.

**Comment by plaplant** [comment]
@BradGreig thanks! I'll try that in the meantime.

**Comment by steven-murray** [comment]
We're thinking at this stage that we don't want to make it easy for users to break the implicit trapezoidal integration between cadences. Allowing arbitrary redshift inputs may make that too simple for users. The defaults for ZPRIME_STEP_FACTOR are chosen such that convergence is achieved. The default node redshifts in the lightcone should be closely spaced enough that no cosmic evolution is appreciable between nodes, therefore you can just take the closest node redshift to your desired comparison.

If you want finer cadence you can always decrease the step factor. 

We may consider allowing the user to input an _extra_ set of redshifts that augment the scrolling redshifts.

**Comment by steven-murray** [comment]
Note that this might be related to a recent PR which added the ability to run arbitrary callback functions on the lightcone node redshifts as it runs.

**Comment by plaplant** [comment]
@steven-murray Thanks for getting back to me. In practice we've just been interpolating between redshift nodes, and the intervals are small enough that I don't think it's _that_ wrong. This is resolved from our point of view, feel free to close this issue if you'd like.
