### ISSUE TITLE
[BUG] Minimum dependency on pytest

### ISSUE THREAD

**Issue by BradGreig** [21cmfast/21cmFAST#139]
**Describe the bug:**
Following updates to the testing, it now appears there are minimum version requirements for `pytest` and `pytest-remotedata`. Without correct versioning, `pytest` will not work locally.

**Details:**
Unsurprisingly, I had an old version of `pytest` (~3.4). Updating to the latest `pytest` (5.4.1) did not immediately resolve the issue. I updated `pytest-cov` from 2.6->2.8, which also did not resolve the issue. Finally, updating `pytest-remotedata` to the latest version (0.3.2) resolved issues 

I think minimum requirements of `pytest` need to be > 5.0.0, most importantly `pytest-remotedata` > 0.3.1 (maybe 0.3.0, but not sure).

**Comment by steven-murray** [comment]
Hmmm, thanks for pointing it out! I'll update the requirements.
