### ISSUE TITLE
[Feature Req.] Better Warnings from C code

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#14]
This is a copy/restatement of https://github.com/BradGreig/Hybrid21CM/issues/15

**Is your feature request related to a problem? Please describe.**

While the `printf` warnings issued in the C code are necessary, they do not have the flexibility and power of Python warnings. For example, Python warnings are issued once per warning per session, while the C warnings will print ad infinitum (this can be tedious in an MCMC setting). 

**Describe the solution you'd like**

Warnings in C cannot be made a part of the new Exception system, I'm pretty sure. However it would be nice to be able to capture them in Python, and display them as Python warnings, if possible.

**Describe alternatives you've considered**

Another alternative is to remove all printed warnings, and make them formal exceptions, or at least allow them to be filtered by log-level.

Another alternative is to try to implement some of the functionality of Python warnings in the C code (i.e. check if the warning has been issued before, and if so, don't print it).

**Comment by steven-murray** [comment]
Some considerations of the different options:

1. **Capturing warnings and re-emitting in Python**: This should be able to be done by capturing stderr/stdout into a buffer, and replaying the buffer once the C function has exited. However, this may introduce the problem that some kind of bad thing happens in the C, and the LOG is not printed at all (because it exits before returning to python). In general, for long-running C functions, just the delay between the occurrence of the warning and its display may cause some issues. Perhaps this can be avoided somehow, but I haven't thought of how yet.
2. **Make all warnings formal exceptions:** this doesn't seem like it will do what we want. A formal exception is useful for propagating through the stack, however a warning is not really an exception -- we don't want to stop execution at that point. 
3. **Allow filtering by log-level:** This is already implemented. At this point, all warnings are implemented via the `LOG_WARNING` macro, which prints nothing if the log-level is lower than `WARNING`. That means that if the user doesn't want to see any warnings, they can explicitly ignore them by _re-installing_ the code. This does not do everything we might want: it doesn't check if the warning has been printed before in a particular session and ignore it from then on. 
4. **Implement some of the warning functionality in C:** There are two main things we might want here. One is to ignore the warning if it has exactly the same message after the first time it's printed. The second thing is to be able catch the warning (either from C or Python) and not print it at all, if the user knows that they don't care about that warning. Both of these are tricky in C, as far as I can tell. To know if a warning has been previously issued, you need some way of storing the message in state across the session and checking against it. 

My feeling is that (1) is going to the most reasonable. Perhaps a way around some of the downsides there is to make it optional from python (maybe a config value can be "catch_c_warnings", and if True, it will buffer the warnings). 

What do you think @BradGreig ?

**Comment by BradGreig** [comment]
I would tend to agree with (1). I don't think there should be ad infinitum error/warning messages produced during the MCMC. In most cases, an error/warning should only be an edge case. Other pre-checks etc., should catch a lot of other issues.

**Comment by steven-murray** [comment]
Thinking about this more, I just don't really think there's any good way of doing this. Some warnings you definitely _want_ to be displayed whenever they come up, because it's possibly something that happens for a given range of parameters, and you want to know it every time you hit those parameters. 

Others would be fine to print just once in say an MCMC run (eg. "your resolution is too low"), but then you want it to print again if for some reason you started another MCMC, or just ran another box, in the same session.

I really don't think capturing and re-emitting in python is going to be very successful. There's just too many complexities involved, it will be too brittle. 
The only way I could then think of doing it is to store a little buffer of messages in a global C variable somewhere, and create a logging macro like `LOG_WARNING_ONCE`, which saves its message in the buffer, and checks that buffer before it prints it. This would also be pretty complex, because how big do you make the buffer? You could _maybe_ get around some of my above concerns by having arguments in the printed string, so that if you change the resolution and re-run, if the resolution is still too small, it will still print the warning. But that might not work for everything.

In the end, the potential gain from this, given that the user can already filter out warnings completely -- even if they have to post-process it -- is probably minimal. 

I'm going to set it to a v4 update, because I don't think it's currently necessary. We can also close the issue if we think it's just not going to happen ever, @BradGreig .


The only way I could think of doing this

**Comment by BradGreig** [comment]
@steven-murray, yeah, I tend to agree with all this. I think its fine to leave this hanging around for now, perhaps we come across a sensible way of doing this along the way.
