### ISSUE TITLE
PhotonCon crashed

### ISSUE THREAD

**Issue by qyx268** [21cmfast/21cmFAST#144]
**Describe the bug:**

I think this line suggests that the program crashed due to a bug related to photon conservation.
`2020-05-17 19:51:09 | DEBUG   | IonisationBox.c | ComputeIonizedBox:156 [pid=234219] | original redshift=5.261127, updated redshift=nan delta-z = nan       `              

At first, I thought it was due to the limited redshift range in InitialisePhotonCons. It was set to z=5 while the lightcone was requested with redshift=4.9. However, after increasing a_end to z=4.9 and rerunning without any cached files, the program crashed again at the same redshift. I suspected "delta-z" could be larger than 0.3 for photon conservation calibration and therefore with an original redshift = 5.26, the updated one could be smaller than 4.9. However, after reducing from z=4.9 to z=4.4, the program (with cached files) still crashed...
                                                          
**To Reproduce:**
The following set of parameters is causing this problem.
astro_params = py21cmfast.AstroParams(ALPHA_ESC=-0.5782171938644294,
                                      ALPHA_STAR=0.2931801482826073,
                                      F_ESC10=np.log10(0.06528048324333377),
                                      F_STAR10=np.log10(0.04046237545524282),
                                      M_TURN=np.log10(1222992760.4016855),
                                      t_STAR=0.5344442329701387)
flag_options = py21cmfast.FlagOptions(INHOMO_RECO=True, PHOTON_CONS=True, USE_MASS_DEPENDENT_ZETA=True)
user_params = py21cmfast.UserParams(USE_FFTW_WISDOM=True)
py21cmfast.global_params.Z_HEAT_MAX=20.0
py21cmfast.global_params.ZPRIME_STEP_FACTOR= 1.02

py21cmfast.run_lightcone(redshift=4.9, user_params=user_params, astro_params=astro_params, flag_options=flag_options,random_seed=1993)

**Expected behavior:**

**Details:**
 - OS: linux (nefertem)
 - Python Version: 3.6.5
 - Relevant compiler versions:
 - Relevant package versions:

**Additional context**

**Comment by qyx268** [comment]
I found the array NeutralFractions has a minimum of 0.029 which is larger than PhotonConsAsymptoteTo (0.01). This led 
`*absolute_delta_z = gsl_spline_eval(deltaz_spline_for_photoncons, global_params.PhotonConsAsymptoteTo, deltaz_spline_for_photoncons_acc);`
to return NaN.

**Comment by BradGreig** [comment]
Hey @qyx268, you almost had it right, but missed one thing.

I have created a new branch, `expand_photoncons_range` to address this. As you have identified the photon non-conservation correction is hard coded to a specific redshift, being z = 5. This appears in two places, you missed the one where it is more important. Now, this choice was selected to be beyond reionisation, hence there wasn't a concern about this value. Now, it appears you are pushing to even lower redshifts (z < 5).

As such, I have allowed this endpoint to now be a variable that the user can modify, found to be `global_params.PhotonConsEndCalibz`. Its placed here as its something all most all users will never care about. Its default will remain at z = 5, as I am relatively confident its been thoroughly tested for this. Going below this, I am not sure how stable things are going to be, but, its now a parameter you can modify. Thus, in your case, set it to be z = 4.9, or below.

This now highlights that a warning should appear if the user passes a redshift below this value. This is trivial for the `run_lightcone` function as it has access to the end redshift of the light-cone. However, if one calls the `run_coeval` function, the photon non-conservation correction need not have access to the lowest redshift that the user would like. If the user passes a list of redshifts, one can assume the lowest redshift of the list is the equivalent to the end of the lightcone. However, this need not always be the case. To me, it doesn't make sense to only provide a warning in `run_lightcone` and leave the user blind to this in the `run_coeval` case. @steven-murray, your thoughts on a robust way to provide a warning for this scenario across the `run_coeval` and 'run_lightcone' functions?

**Comment by BradGreig** [comment]
Actually, upon further inspection, I think it is ok to throw up an equivalent error across `run_lightcone` and `run_coeval'. I'll put that in and setup a PR request.

**Comment by qyx268** [comment]
@BradGreig thx for looking into this, I did miss the other hard-coded part. I also had a branch (photonCon_minZ), trying to assign PhotonConsEndCalibz dynamically according to what the user has (i.e. redshift for lightcone, and min(redshifts) for coeval).
