### ISSUE TITLE
config directory cannot be set inside python script [BUG]

### ISSUE THREAD

**Issue by sabrinastronomy** [21cmfast/21cmFAST#148]
**Describe the bug:**
When setting  `py21cmfast.config['direc'] = directory` in a python script before running `coeval_sliceplot`, the directory set will be ignored and instead replaced with the one found under `direc: /test/21cmFAST/` found in `config.yml`.

**To Reproduce:**
```
import py21cmfast as p21c
import os
from py21cmfast import plotting
import matplotlib.pyplot as plt
import logging, sys
logging.basicConfig(stream=sys.stdout)
logger = logging.getLogger('21cmFAST')
logger.setLevel(logging.INFO)
print("successfully imported packages")
# generate fields for various z values
initial_conditions = p21c.initial_conditions(
             user_params = {"HII_DIM": 50, "BOX_LEN": 50},
             cosmo_params = p21c.CosmoParams(SIGMA_8=0.8))
plotting.coeval_sliceplot(initial_conditions, "hires_density") # plotting the high resolution density 
```
**Expected behavior:**
`py21cmfast.config['direc'] = directory` should override the directory set in `config.yml`.

**Details:**
 - OS: Running on Beluga Compute Canada: https://docs.computecanada.ca/wiki/B%C3%A9luga/en
 - Python Version: Python 3.7.4

**Comment by BradGreig** [comment]
Hi @sabrinastronomy, I just had a mess around with this and I had no problems. Changing the directory within Python stored (and read) all data to where ever I set the directory to be. Are you getting a particular error message?

**Comment by sabrinastronomy** [comment]
Sorry--this looks to be my issue. Oops, I was setting the directory variable post setting the initial conditions. I apologize for wasting time on this.

**Comment by steven-murray** [comment]
Great! Glad you got it fixed :-)
