### ISSUE TITLE
[BUG] In first couple of steps for mini halos

### ISSUE THREAD

**Issue by BradGreig** [21cmfast/21cmFAST#153]
**Describe the bug:**
Potentially two separate issues: 
1) if selecting a user defined Z_HEAT_MAX and running at high redshift it will crash.
2) Ionisation box doesn't seem to use the previous density field at the second redshift in the scrolling loop.

**To Reproduce:**
For 1): run_coeval(
        redshift=18,
        regenerate=True,
        write=False,
        z_heat_max = 25,
        zprime_step_factor=1.2,
        ) 

It'll start at z = 26.36, then next iteration will be z = 21.8 (prev_z = 26.36). But, ionize_box won't find a box at 26.36 and thus fail (it'll fail because ionise box will populate it with an empty box as prev_z > Z_HEAT_MAX.

For 2): run_coeval(
        redshift=18,
        regenerate=True,
        write=False,
        zprime_step_factor=1.2,
        )

It'll start at z = 38.398, then next iteration will be z = 31.8 (prev_z = 38.398). But in ionize_box, the variables (output in ULTRA-DEBUG) prev_min_density and prev_max_density will be 0.00. Yet, this is the second iteration, and these should be non-zero, as the ionisation box at z = 38.398 is the first redshift (and min_density and max_density at z = 38.398 are non-zero). Therefore, on second iteration it doesn't seem to use the prev_density_field (the one from z=38.398). Not sure if this behaviour is related to the first (it should be as in both instances prev_z > Z_HEAT_MAX, however, it results in two different behaviours which is weird to me).

**Comment by BradGreig** [comment]
By the way, this behaviour occurs on the master branch

**Comment by BradGreig** [comment]
One possible solution I came up with was to replace this code in `ionize_box` in the `run_coeval` fuction:

```previous_perturbed_field=(
                    None
                    if iz == 0 or not flag_options.USE_MINI_HALOS
                    else (
                        perturb[redshift.index(redshifts[iz - 1])]
                        if redshifts[iz - 1] in redshift
                        else None
                    )
                ),
```

with:

```
previous_perturbed_field=(
                    None
                    if iz == 0 or not flag_options.USE_MINI_HALOS
                    else (
                        perturb[redshift.index(redshifts[iz - 1])]
                        if redshifts[iz - 1] in redshift
                        else perturb_field(
                                       redshift=z,
                                       regenerate=regenerate,
                                       write=write,
                                       direc=direc,
                                   )
                    )
                ),
```

Because it seemed like it couldn't find the appropriate perturb field box (previous ionize box would have been passed properly). It seemed to work (for solving 1), didn't check for 2)). However, I would expect issues to still arise if it attempts to read from file.

**Comment by qyx268** [comment]
Sorry, most tests regarding minihalos were done using lightcone. I must have missed this. 

I think it is more related to the scenario when we need previous snapshot (e.g. `if flag_options.INHOMO_RECO or flag_options.USE_TS_FLUCT`). However, without minihalos, we did not need information from previous perturb field, therefore we didn't store those perturb fileds. I think to solve both two issues, we just need to add perturb filed of all z in `redshifts` rather than in `redshift`.

p.s. the changes you made might not work properly because `z` here is the current redshift rather than previous redshift.
