### ISSUE TITLE
[BUG] Broken assertion when passing single lightcone or global quantity

### ISSUE THREAD

**Issue by adampbeardsley** [21cmfast/21cmFAST#155]
**Describe the bug:**

**To Reproduce:**
```
lightcone = p21c.run_lightcone(
    redshift = 6.0,
    max_redshift = 20.0,
    lightcone_quantities=("brightness_temp"),
    global_quantities=("brightness_temp"),
    direc='_cache'
)
```
Results in:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-12-efb8dfcfd5a2> in <module>
----> 1 lightcone = p21c.run_lightcone(
      2     redshift = 6.0,
      3     max_redshift = 20.0,
      4     lightcone_quantities=("brightness_temp"),
      5     global_quantities=("brightness_temp"),

/data4/beards/src/anaconda3/envs/21cmFAST/lib/python3.8/site-packages/py21cmfast/wrapper.py in run_lightcone(redshift, max_redshift, user_params, cosmo_params, astro_params, flag_options, regenerate, write, lightcone_quantities, global_quantities, direc, init_box, perturb, random_seed, use_interp_perturb_field, cleanup, **global_kwargs)
   2142             arrays_only=True, lightcone_only=True, as_dict=True
   2143         )
-> 2144         assert all(
   2145             q in _fld_names.keys() for q in lightcone_quantities
   2146         ), "invalid lightcone_quantity passed."

AssertionError: invalid lightcone_quantity passed.
```
Similar error for `global_quanitity` if I get passed the `lightcone_quanitity`.

**Expected behavior:**

I expect the above code to run and only interpolate the brightness temperature to the lightcone and global quantities.

**Details:**
 - OS: Linux
 - Python Version: 3.8
 - Relevant compiler versions:
 - Relevant package versions:

**Additional context**

A simple work around is to make my argument a single-valued list. The problem seems to be in the ` for q in lightcone_quantities` clause because if `lightcone_quantities` is a single string, the `for` loop iterates through the characters of the string.

**Comment by steven-murray** [comment]
I think the thing is here that you're expecting `("brightness_temp")` to be a single-valued tuple, but it's not. To create that you need `("brightness_temp",)`. I agree this is confusing behaviour. Probably adding an assertion that the thing that's passed is not a string is the best idea.

**Comment by adampbeardsley** [comment]
Ah, you're right. This is my fault, don't think it needs to be changed.
