### ISSUE TITLE
RAM gradually builds up when running 21cmmc (memory leak?)

### ISSUE THREAD

**Issue by qyx268** [21cmfast/21cmFAST#161]
**Describe the bug:**
There seems to be still memory leak in the code. When running 21cmmc, the RAM gradually builds up after hundreds of simulations. I did a quick check, it doesn't seem to be related to fftw arrays... 

**To Reproduce:**
Just run a 21cmmc simulation with USE_MASS_DEPENDENT_ZETA and INHOMO_RECO (haven't checked if these are necessary) and monitor the RAM usage.

**Expected behavior:**

**Details:**
 - Python Version: [e.g. 22]
 - Relevant compiler versions:
 - Relevant package versions:

**Additional context**

**Comment by steven-murray** [comment]
If you have a bit of time, can you try modifying the
`devel/simulate_mcmc_memory_leak.py` script, and running it through
valgrind? Instructions are in the notes_for_developers.rst in the docs
folder.
