### ISSUE TITLE
[BUG] hangs when USE_MASS_DEPENDENT_ZETA=True

### ISSUE THREAD

**Issue by binnietom** [21cmfast/21cmFAST#166]
**Describe the bug:**
Hanging when calling a chain with USE_MASS_DEPENDENT_ZETA=True

**To Reproduce:**
Attached MWE notebook.
[mass_d_zeta_MWE.ipynb.zip](https://github.com/21cmfast/21cmFAST/files/5151053/mass_d_zeta_MWE.ipynb.zip)

**Expected behaviour:**
The chain is built with core and likelihood modules, then the likelihood_ function should run 1 sample.
(The formatting is motivated by being mpi and pymultinest friendly)

**Details:**
Both 21cmfast and 21cmmc are up-to-date master branches (31/8/20).

**Additional context**
No outputted errors with DEBUG=True.
Brightness_temperature h5 files are created in the Cache.

**Comment by BradGreig** [comment]
Hi @binnietom , if you are using the up-to-date master, can you please make sure to pass the `USE_INTERPOLATION_TABLES=True` flag to `UserParams`. The default behaviour is to calculate all the integrals exactly. 

Try that, if it is still having issues let me know and I'll look into it in more detail

**Comment by binnietom** [comment]
It works, thanks. Although each sample is now about 3/4 times slower now, is there any way around this? The only thing I can think of is backtracking through my git pulls.

**Comment by steven-murray** [comment]
Using interpolation tables used to be the default. Using them shouldn't
slow anything down. Do you have `PERTURB_ON_HIGH_RES` set to False?

**Comment by binnietom** [comment]
Yes, I did. thanks.

**Comment by BradGreig** [comment]
Hi @binnietom, I don't understand why it would be 3-4 times slower. Can you please output `UserParams`, `AstroParams` and `FlagOptions` (or a log file where this is output) between the latest branch, and the old version where it was faster. Also, are you sure the old version wasn't reading from cache or something?

**Comment by binnietom** [comment]
It is working consistently well with the above flag corrections. The previous may well have been unintentionally cached.

Here is an example log: 

Arguments: (8.363599649810794, 8.55087146421052, UserParams(BOX_LEN:250.0, DIM:384, HII_DIM:128, HMF:1, NO_RNG:False, N_THREADS:1, PERTURB_ON_HIGH_RES:False,
POWER_SPECTRUM:0, USE_FFTW_WISDOM:False, USE_INTERPOLATION_TABLES:True, USE_RELATIVE_VELOCITIES:False), CosmoParams(OMb:0.04897468161869667, OMm:0.30964144154550644,
POWER_INDEX:0.9665, SIGMA_8:0.8102, hlittle:0.6766), AstroParams(ALPHA_ESC:-0.5, ALPHA_STAR:0.5, F_ESC10:0.1, F_ESC7_MINI:0.01, F_H2_SHIELD:0.0, F_STAR10:0.05011872336272722,
F_STAR7_MINI:0.01, HII_EFF_FACTOR:89.78219985961914, ION_Tvir_MIN:47633.36706146258, L_X:8.299804440000439e+41, L_X_MINI:1e+40, M_TURN:501187233.6272715, NU_X_THRESH:194.45151090621948,
N_RSD_STEPS:20, R_BUBBLE_MAX:50.0, X_RAY_SPEC_INDEX:2.94932222366333, X_RAY_Tvir_MIN:47633.36706146258, t_STAR:0.5), FlagOptions(INHOMO_RECO:True, M_MIN_in_Mass:False,
PHOTON_CONS:False, SUBCELL_RSD:False, USE_HALO_FIELD:False, USE_MASS_DEPENDENT_ZETA:True, USE_MINI_HALOS:False, USE_TS_FLUCT:True), 8.363599649810794, False,

PerturbedField(UserParams(BOX_LEN:250.0, DIM:384, HII_DIM:128, HMF:1, NO_RNG:False, N_THREADS:1, PERTURB_ON_HIGH_RES:False, POWER_SPECTRUM:0, USE_FFTW_WISDOM:False,
USE_INTERPOLATION_TABLES:True, USE_RELATIVE_VELOCITIES:False); CosmoParams(OMb:0.04897468161869667, OMm:0.30964144154550644, POWER_INDEX:0.9665, SIGMA_8:0.8102,
hlittle:0.6766); redshift:8.363599649810794; 

GlobalParams(CRIT_DENS_TRANSITION=1.5;DELTA_CRIT_MODE=1;DELTA_R_FACTOR=1.100000023841858;EVOLVE_DENSITY_LINEARLY=0;
FILTER=0;HALO_FILTER=0;INITIAL_REDSHIFT=300.0;MIN_DENSITY_LOW_LIMIT=9.000000034120603e-08;M_MAX_INTEGRAL=1.0000000272564224e+16;M_MIN_INTEGRAL=100000.0;M_WDM=2.0;
NBINS_LF=100;OMk=0.0;OMn=0.0;OMr=8.600000001024455e-05;OMtot=1.0;OPTIMIZE=0;OPTIMIZE_MIN_MASS=99999997952.0;P_CUTOFF=0;PhotonConsAsymptoteTo=0.009999999776482582;

PhotonConsEnd=0.30000001192092896;PhotonConsEndCalibz=5.0;PhotonConsStart=0.9950000047683716;R_BUBBLE_MIN=0.6203504800796509;R_OVERLAP_FACTOR=1.0;
R_smooth_density=0.20000000298023224;RecombPhotonCons=0;SECOND_ORDER_LPT_CORRECTIONS=1;SHETH_b=0.15000000596046448;SHETH_c=0.05000000074505806;
SMOOTH_EVOLVED_DENSITY_FIELD=0;T_RE=20000.0;Y_He=0.24500000476837158;Zreion_HeII=3.0;g_x=1.5;wl=-1.0); v3.0)_random_seed=131460336394, 

TsBox(UserParams(BOX_LEN:250.0, DIM:384, HII_DIM:128, HMF:1, NO_RNG:False, N_THREADS:1, PERTURB_ON_HIGH_RES:False, POWER_SPECTRUM:0,
USE_FFTW_WISDOM:False, USE_INTERPOLATION_TABLES:True, USE_RELATIVE_VELOCITIES:False); 

CosmoParams(OMb:0.04897468161869667, OMm:0.30964144154550644,
POWER_INDEX:0.9665, SIGMA_8:0.8102, hlittle:0.6766); redshift:8.55087146421052; FlagOptions(INHOMO_RECO:True, M_MIN_in_Mass:False, PHOTON_CONS:False,
SUBCELL_RSD:False, USE_HALO_FIELD:False, USE_MASS_DEPENDENT_ZETA:True, USE_MINI_HALOS:False, USE_TS_FLUCT:True); 

AstroParams(ALPHA_ESC:-0.5, ALPHA_STAR:0.5, 
F_ESC10:0.1, F_ESC7_MINI:0.01, F_H2_SHIELD:0.0, F_STAR10:0.05011872336272722, F_STAR7_MINI:0.01, HII_EFF_FACTOR:89.78219985961914, ION_Tvir_MIN:47633.36706146258,
L_X:8.299804440000439e+41, L_X_MINI:1e+40, M_TURN:501187233.6272715, NU_X_THRESH:194.45151090621948, N_RSD_STEPS:20, R_BUBBLE_MAX:50.0, 
X_RAY_SPEC_INDEX:2.94932222366333, X_RAY_Tvir_MIN:47633.36706146258, t_STAR:0.5);

GlobalParams(ALPHA_UVB=5.0;CLUMPING_FACTOR=2.0;CRIT_DENS_TRANSITION=1.5;DELTA_CRIT_MODE=1;DELTA_R_FACTOR=1.100000023841858;
DELTA_R_HII_FACTOR=1.100000023841858;EVOLVE_DENSITY_LINEARLY=0;FILTER=0;FIND_BUBBLE_ALGORITHM=2;HALO_FILTER=0;HEAT_FILTER=0;HII_FILTER=1;
HII_ROUND_ERR=9.999999747378752e-06;INITIAL_REDSHIFT=300.0;MIN_DENSITY_LOW_LIMIT=9.000000034120603e-08;M_MAX_INTEGRAL=1.0000000272564224e+16;M_MIN_INTEGRAL=100000.0;
M_WDM=2.0;NBINS_LF=100;NUM_FILTER_STEPS_FOR_Ts=40;NU_X_BAND_MAX=2000.0;NU_X_MAX=10000.0;N_POISSON=5;OMk=0.0;OMn=0.0;OMr=8.600000001024455e-05;OMtot=1.0;OPTIMIZE=0;
OPTIMIZE_MIN_MASS=99999997952.0;P_CUTOFF=0;PhotonConsAsymptoteTo=0.009999999776482582;PhotonConsEnd=0.30000001192092896;PhotonConsEndCalibz=5.0;
PhotonConsStart=0.9950000047683716;Pop=2;Pop2_ion=5000.0;Pop3_ion=44021.0;R_BUBBLE_MIN=0.6203504800796509;R_OVERLAP_FACTOR=1.0;R_XLy_MAX=500.0;
R_smooth_density=0.20000000298023224;RecombPhotonCons=0;SECOND_ORDER_LPT_CORRECTIONS=1;SHETH_b=0.15000000596046448;SHETH_c=0.05000000074505806;
SMOOTH_EVOLVED_DENSITY_FIELD=0;TK_at_Z_HEAT_MAX=-1.0;T_RE=20000.0;XION_at_Z_HEAT_MAX=-1.0;Y_He=0.24500000476837158;
ZPRIME_STEP_FACTOR=1.0199999809265137;Z_HEAT_MAX=35.0;Zreion_HeII=3.0;g_x=1.5;wl=-1.0); v3.0)_random_seed=131460336394)

**Comment by BradGreig** [comment]
Hi @binnietom, looking at the log it has `USE_TS_FLUCT = True`, yet in your MWE this is False. Not sure if the log came from the MWE or from your own work.
