### ISSUE TITLE
[Feature Req.] More flexible data saving/loading

### ISSUE THREAD

**Issue by dprelogo** [21cmfast/21cmFAST#170]
**Is your feature request related to a problem? Please describe.**
At the moment, whenever `.save` or `.read` functions are called, the only option is to save/read directly from the filename. This is good as it is self-consistent, but is not very flexible. For example I would like to save a lightcone object, but in the same hdf5 would like to have additional data. 

**Describe the solution you'd like**
SImple solution would be to enable the user to pass opened hdf5 `file` or `group`. In that way structure would still be consistent and user would have the ability to save and load objects as a part of their larger hdf5 files.

**Comment by steven-murray** [comment]
This would also enable reading parts of objects, which is probably
something we'll want to enable better memory management down the line.

**Comment by qyx268** [comment]
Generalizing the `save` and `read` functions might need a bit more development as users might desire different kinds of flexibility. Is it easier at the moment to save separately using `h5py`?
