### ISSUE TITLE
No error raised or warning when a decreasing redshifts list is used in .wrapper.compute_tau

### ISSUE THREAD

**Issue by YihaoZhou27** [21cmfast/21cmFAST#176]
**Describe the bug:**
The function `.wrapper.compute_tau` assumes the input `redshifts` is an increasing list. When the user inputs a decreasing redshift list, it doesn’t raise an error but gets a tau value which doesn’t depend on the input parameters.

**To Reproduce:**
1. Call `.wrapper.compute_tau` several times with the same `user_params`, `cosmo_params`, and a `redshifts` which is decreasing, but different gloabl_xHI lists each time.
2. You will get the same output.

**Expected behavior:**
When the user inputs a decreasing redshift list, the function works as well or raise an error.

**Additional context**
In `UsefulFunctions.c` codes, when it calls `ComputeTau` , it sets the `zstart` to be 0 instead of redshift_list[0], making the raise-error codes based on whether` zstart >= zend` useless.

**Comment by BradGreig** [comment]
Hi @YihaoZhou27 thank you for pointing this out. I have submitted a PR to add in an error message indicating these quantities must be ascending.
