### ISSUE TITLE
Turning USE_RELATIVE_VELOCITIES to True screws up density lightcones [BUG]

### ISSUE THREAD

**Issue by JulianBMunoz** [21cmfast/21cmFAST#191]
**Describe the bug:**

Including relvels makes the lightcones appear wrong, both on T21 but also on densities (attached both with and without USE_RELATIVE_VELOCITIES: True; densities should *not* depend on the relative velocities at all). Densities and velocities look fine out of initial_conditions.

![Screen Shot 2020-11-17 at 2 52 41 PM](https://user-images.githubusercontent.com/22434409/99440417-8f7e3680-28e4-11eb-8fd2-92b271c2870d.png)
![screen_shot_2020-11-16_at_11 11 03_pm](https://user-images.githubusercontent.com/22434409/99440113-154db200-28e4-11eb-9033-2a312c5e76e3.png)

**To Reproduce:**
1. Run initial conditions with:
user_params = {"HII_DIM":HII_DIM, "BOX_LEN": BOX_LEN, "USE_FFTW_WISDOM": True, 'USE_INTERPOLATION_TABLES': True,
              "USE_RELATIVE_VELOCITIES": True, "POWER_SPECTRUM": 5}
2. Run lightcone with:
lightcone_fid_vcb = p21c.run_lightcone(
        redshift = 20.0,
        init_box = initial_conditions,
        flag_options = flag_options_fid,
        astro_params = astro_params_fid,
        lightcone_quantities=lightcone_quantities,
        global_quantities=lightcone_quantities,
        random_seed = random_seed,
        direc = output_dir,
        write=True
)

3. Plot T21 or densities in the lightcone. 

**Expected behavior:**

I have checked that using “USE_RELATIVE_VELOCITIES”: False, “POWER_SPECTRUM”: 5 I get sensible results, but If I set “USE_RELATIVE_VELOCITIES”: True

I’ve checked that doing plotting.coeval_sliceplot(initial_conditions, “hires/lowres_density”) is normal (the same as with no relvels), so something must go wrong when processing the ICs into the lightcone or into the coeval boxes (which also look noisy and insane, also attached).

![screen_shot_2020-11-16_at_11 12 09_pm](https://user-images.githubusercontent.com/22434409/99440127-18e13900-28e4-11eb-9fa5-23b7e750986c.png)

I'm checking if setting EVOLVE_DENSITY_LINEARLY=True fixes it, to see if the problem is in perturb.c. It looks like memory corruption to me.

**Comment by JulianBMunoz** [comment]
UPDATE: setting EVOLVE_DENSITY_LINEARLY=True solves the issue, so it has to do with the perturb part of the code. Attached is lightcone of densities with USE_RELATIVE_VELOCITIES: True

![Screen Shot 2020-11-17 at 3 40 05 PM](https://user-images.githubusercontent.com/22434409/99445129-2b12a580-28eb-11eb-83a1-3c4da3ea2173.png)

**Comment by qyx268** [comment]
I haven't started using with the relative velocity yet, which I should... But I was going to comment that we don't use the IC when generating a LC. So it has to do with the perturb field. However, I also don't see any codes in `PerturbField.c` checking for the `USE_RELATIVE_VELOCITIES` flag. Then judging from the timing when @catherinewatkinson started implementing `PERTURB_ON_HIGH_RES`, I'm guessing here that `USE_RELATIVE_VELOCITIES` might be also implemented to work with `PERTURB_ON_HIGH_RES`. Can you please try with `PERTURB_ON_HIGH_RES=1`?

**Comment by JulianBMunoz** [comment]
Thanks @qyx268!

It's not PERTURB_ON_HIGH_RES, but the 2LPT part. There was an error introduced when writing the 2LPT part of the generateICs.c, which for some reason did not FFTW the v_2LPT boxes if USE_RELATIVE_VELOCITIES == 1 (there was an execute() missing). Steven and I have fixed this on the fix2lptrelvel branch.
