### ISSUE TITLE
velocity on y and z direction seems odd

### ISSUE THREAD

**Issue by qyx268** [21cmfast/21cmFAST#195]
**Describe the bug:**

Velocity components on z and y direction looks elongated. The co-evolve box of density, vz, vy and vx is shown below

100Mpc box:
![image](https://user-images.githubusercontent.com/15994713/101075885-e5203780-35a2-11eb-82fd-ca70e60ee273.png)
1Gpc box:
![image](https://user-images.githubusercontent.com/15994713/101076025-126ce580-35a3-11eb-9d04-ea11d01febef.png)

**To Reproduce:**
Just add new component in `PerturbedField` to also output velocity on y and x direction (see branch store_allV)

**Expected behavior:**

**Details:**
 - OS: Linux nefertem.sns.it 2.6.32-504.hz100.el6.x86_64 #1 SMP Fri Oct 31 20:08:27 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
 - Python Version: 3.6.5

**Additional context**

Better to first check with 2LPT off. 

Again, do we have similar outputs from previous version of 21cmFAST?

**Comment by qyx268** [comment]
I dug a bit. looks like the pattern comes from the IC.

Top: hires_v[zyx]
Middle: hires_v[zyx]_2LPT
Bottom: hires_v[zyx] - hires_v[zyx]_2LPT
Left to Right: vz, vy, vx
![IC_highres_v](https://user-images.githubusercontent.com/15994713/101095088-ae0b4f80-35bd-11eb-9eb9-74b7a5eb8a2c.jpg)

The density looks okay though...
Left to Right: projection of yz, zx and xy
![IC_highres_density](https://user-images.githubusercontent.com/15994713/101095423-31c53c00-35be-11eb-9f3c-9bb7b3d56897.jpg)

**Comment by andreimesinger** [comment]
this looks like it might be a memory /fft /initialization issue after the vx calculation…  vx is the first field to be computed, and then vy, then vz.  the same code is used.  but it could be that things are not being reset properly after the first vx

**Comment by qyx268** [comment]
that's what i thought. but can't find any trace of it

**Comment by andreimesinger** [comment]
is it also true if you turn off hi res?

the only other thing i can think of are the complex conjugate adjustments in init, but i doubt there is a bug that hasn't been found here...

**Comment by qyx268** [comment]
no, i havent try turn off hi-res (and when hi-res is on, we dont output low-res quantities unfortunately). but from the code, i dont see why low-res will behave differently... i will generate an IC with hi-res off then just to double-check.

I was going to ask if `adj_complex_conj` is correct. but i compared with the old code. they look identical...

**Comment by qyx268** [comment]
i'll also do a run with fftw off...

**Comment by andreimesinger** [comment]
well, that is not a guarantee it is correct :-)

**Comment by qyx268** [comment]
let's first see what the runs without hi-res and without fftw show...

**Comment by BradGreig** [comment]
This isn't a bug, this is just the normal behaviour.

The velocity components are obtained by filtering the density field along each of the 3 directions (i.e. x, y, z). Thus, you expect to have smoothed direction dependent structures. See below from a much older version of 21cmFAST (~5 years old). These are the ICs from a 300 Mpc box, HII_DIM = 150 with no 2LPT.

[SlicePlot.pdf](https://github.com/21cmfast/21cmFAST/files/5639841/SlicePlot.pdf)

**Comment by andreimesinger** [comment]
how is having a preferred velocity direction not a bug?

**Comment by qyx268** [comment]
perhaps the smooth direction happens to be in the yz plane? 

In any case, high-res or without fftw returns the same velocity structure...

**Comment by andreimesinger** [comment]
it might help manually switching the order of the velocity field calculations, and also looking into the complex conjugate adjustments, trying to see where the symmetry is broken

**Comment by qyx268** [comment]
swapping the order gives the result result. I'll look into the complex conjugate adjustments...

**Comment by qyx268** [comment]
For HIRES_box[C_INDEX(i,j,k)], when i change the order of adjusting the complex conjugate on loop i and loop j in `adj_complex_conj`, I do get different velocity maps. Looks like some velocity leaks from x (right) to y(left) from 

j loop in i loop:
![IC_highres_swap](https://user-images.githubusercontent.com/15994713/101267734-6a9b1780-375c-11eb-80f4-e0cb557c9249.png)
to 
i loop in j loop:
![IC_highres_swap_conf](https://user-images.githubusercontent.com/15994713/101267736-6ff86200-375c-11eb-8e54-87e092bb60fa.png)

However, the distortion is still in vz (left) and vy (middle). I'm not sure if this makes any sense...  I assume we want to make all elements below middle and above middle in HIRES_box[C_INDEX(i,j,k)] to have reversed sign of the imaginary part. In this case, swapping the order of the two loops should give the same result.

**Comment by qyx268** [comment]
Er... I found it also depends on how we view the velocity field.

I've alway been plotting velocity[0,:,:], e.g. (this one has a different seed as before because I was trying to see if certain seeds give perference differently)
![IC_highres_seed90](https://user-images.githubusercontent.com/15994713/101267688-cf09a700-375b-11eb-8eaf-4d4a63cc8b96.png)

But if I plot velocity[:,0,:], vy looks okay and the distortion becomes in vx and vz.
![IC_highres_seed90_y](https://user-images.githubusercontent.com/15994713/101267691-d335c480-375b-11eb-80a5-63505a707857.png)

This is what happen if I plot velocity[:,:,0]. Now vz looks okay and the distortion becomes in vx and vy.
![IC_highres_seed90_z](https://user-images.githubusercontent.com/15994713/101267692-d630b500-375b-11eb-9cca-d0bf5d61a0d0.png)

I need to think about what this means...

**Comment by andreimesinger** [comment]
ah, so i then i think i agree with brad that this is not a bug...

velocity fields have long correlation lengths, so if you plot a slice with a thickness of only 1 cell, you can pick up residual bulk flows.  so the image depends a lot on what slice you take.  and i also think your color scheme  here doesn’t help since it makes the field look binary...

for velocities it can be more useful  to project (sum) over a larger length (because they are zero mean, projecting doesn’t saturate out the signal like it would for density).  you should see the behavior that as you increase the projection length, the components start looking the same (and they all start fading away)

**Comment by qyx268** [comment]
no, that's the the case here. If I plot projection of the entire box, I get similar non-zero structures in vz and vy while vx does become all 0. This is when projected onto the yz plane.
![image](https://user-images.githubusercontent.com/15994713/101355318-b05bfb00-3896-11eb-98c2-4731c43c5a3a.png)


The same happen when projected onto zx or xy plane where I will see vy or vz becomes zero while the other components remain.
e.g. projected onto zx plane:
![image](https://user-images.githubusercontent.com/15994713/101355351-ba7df980-3896-11eb-9070-39cc27923c8d.png)

**Comment by andreimesinger** [comment]
yes well it is only gonna average away if you are slicing perpendicular to the velocity component.   so eg vx would average away if you do a slice in yz and project along x…  projecting along another direction will still give you a residual…

you can see this with a simple 2 D example…  say you have a x, y field of vx: 

[0.5, 0]
[-0.5, 0]

here there is no net flow in the vx direction, which you can see by either projecting along x, and getting [0, 0], or averaging over all space and getting 0.  however, if you project the x velocity along the y direction, you get non zero entries [-0.5, 0.5]

so in principle, when visualising velocities, it is good to average over some length along the axis of the velocity component you are plotting...
