### ISSUE TITLE
Can we make fast approximate Fcoll tables? [Feature Req.]

### ISSUE THREAD

**Issue by JulianBMunoz** [21cmfast/21cmFAST#196]
As it stands, it takes a significant amount of time to create Fcoll interpolation tables. This is not a gigantic slowdown for the usual vanilla case, but it is when minihaloes are included. These tables may be approximated quickly and efficiently, reducing the computational overhead to run simulations.

For the old parametrization of Fcoll (before Park+18, where the power-law index alpha*=0 and with a sharp turnover mass Mt) the integrated Fcoll was exactly an erfc (and I found that doing this in 21cmvFAST produced identical results at much faster speed). I have found an approximation for other alpha_*, and will check it against current models. I'm working on branch fast-fcoll-tables.

This could become a flag USE_FAST_TABLES or similar, that the user can turn on. It'll likely sacrifice a bit of precision (given the approximations), but it may be worth it depending on the usage.

**Comment by steven-murray** [comment]
Fixed in #200
