### ISSUE TITLE
Move issues from Hybrid21cm to here

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#2]
Any open issues that pertain to 21cmFAST should be moved here

**Comment by steven-murray** [comment]
@BradGreig this seems to be possible via a link at the bottom-right of each issue, however it seems that I don't have permissions to move them here (or I can't figure it out properly...). Can you have a try of moving the 21cmFAST-specific ones here (and alternatively for the 21CMMC-specific ones)?

**Comment by BradGreig** [comment]
I just tried looking into this, and I cannot do it either. I seem to be able to move it across my own repositories, but not between my own and the organisation. You have write access to Hybrid so it should have been possible if allowed.

**Comment by steven-murray** [comment]
Ah ok. Maybe it doesn't work between user and organisation repos. We can instead copy over relevant material, and link back to the original issue, so people know where to go if it affects them.

**Comment by steven-murray** [comment]
Actually, @BradGreig , can you go here: https://github.com/orgs/21cmfast/people and flip the switch so that you're a public member? It may then work for you (just a hunch).

**Comment by BradGreig** [comment]
Nope, didn't help. It seems that repo's visible under the organisation are not visible from the other repo's

**Comment by steven-murray** [comment]
OK, I've manually moved all the issues over.
