### ISSUE TITLE
More stringent tests

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#20]
While tests cover a lot of the (Python) code currently, there is a concern that the tests aren't very comprehensive in testing the accuracy of the code (physically).

One idea would be to have some scripts that are run on every appropriate PR/merge which run low-res simulations and produce plots which can be viewed by human reviewers. 

This cannot (to my knowledge) be fully automated. However, we can add a checkbox on PR template that ensures that we remember to do this if the PR is sufficiently complex. 

We should also think about adding more unit tests that can be run fully automatically.

**Comment by andreimesinger** [comment]
yes, i think the idea was two-fold: (i) code additions which are optional, should allow to have an automated test, comparing fiducial output against known output (PS evolution), *when the new addition is turned off*.  this should be within some tollerance.  (ii) more generically, the code should be able to be compiled and a simple, low-res run performed, with some summary plots produced (like the classical light cone, <delT>, PS evolution, and maybe also component fields using the slice_plot function) which can be checked by-eye to see if it makes "sense"

**Comment by steven-murray** [comment]
So (i) is like a series of regression tests. That could be done reasonably easily.
(ii) is a bit more complicated in terms of project structure. What I'm thinking is this: make a script (or series of them) in a `manual_tests` directory that makes the relevant plots. Also, add a checkbox on the PR template which ensures that we remember to run that script. The plots output by the script then should be posted as a comment in the PR to be inspected by the reviewer along with the code.
