### ISSUE TITLE
[BUG] Installation from non-git distribution with setuptools-scm

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#212]
As described in comments in #205, it seems that installing from a downloaded zip file from github does not work since we implemented `setuptools-scm`.  Though this is a bit of a corner case, it would be a good idea to enable this.

**Comment by zhangzzk** [comment]
Hi,

I'm trying to modify the internal C code. When I followed the doc to compile the new code:
`    
$ rm -rf build
    $ pip install .
`
I encountered the same bug with the setuptools-scm. Is there any other way I can compile the code?
Thanks for the help!

**Comment by steven-murray** [comment]
Hi @zhangzzk -- the easiest way to modify the code is to clone the git repo, rather than downloading the zip. You can definitely make a fork/branch and modify the code all you like!

**Comment by zhangzzk** [comment]
Thanks for your help!
