### ISSUE TITLE
Corrupted c_21cmfast.abi3.so after successful installation?

### ISSUE THREAD

**Issue by Kai-FengChen** [21cmfast/21cmFAST#214]
Hi,

I've tried to install 21cmFast with pip on a macOS with clang/gsl/fftw installed through brew. I am able to compile and install the package but upon import it, I got the following error

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-342a4a96e579> in <module>
----> 1 import py21cmfast as p21c

~/.pyenv/versions/3.9.1/lib/python3.9/site-packages/py21cmfast/__init__.py in <module>
      6 from os import path
      7
----> 8 from . import cache_tools, inputs, outputs, plotting, wrapper
      9 from ._cfg import config
     10 from ._logging import configure_logging

~/.pyenv/versions/3.9.1/lib/python3.9/site-packages/py21cmfast/cache_tools.py in <module>
      7 from os import path
      8
----> 9 from . import outputs, wrapper
     10 from ._cfg import config
     11 from .wrapper import global_params

~/.pyenv/versions/3.9.1/lib/python3.9/site-packages/py21cmfast/outputs.py in <module>
     27 from ._utils import OutputStruct as _BaseOutputStruct
     28 from ._utils import _check_compatible_inputs
---> 29 from .c_21cmfast import ffi, lib
     30 from .inputs import AstroParams, CosmoParams, FlagOptions, UserParams, global_params
     31

ImportError: dlopen(/Users/kfchen/.pyenv/versions/3.9.1/lib/python3.9/site-packages/py21cmfast/c_21cmfast.abi3.so, 2): Symbol not found: ___kmpc_barrier
  Referenced from: /Users/kfchen/.pyenv/versions/3.9.1/lib/python3.9/site-packages/py21cmfast/c_21cmfast.abi3.so
  Expected in: flat namespace
 in /Users/kfchen/.pyenv/versions/3.9.1/lib/python3.9/site-packages/py21cmfast/c_21cmfast.abi3.so
```

I am on a macOS Catalina (10.15.6) with a python 3.9.1 compiled with clang 11.1.0 installed through brew. I faced other problems when trying to install the package with conda and thought taking care of all the dependencies myself might be an easier route. But is my installation corrupted and maybe some of the c code is not compiled correctly? 

Thanks in advance for the help!

**Comment by qyx268** [comment]
I think that the `.so` file exsits suggests thte compiling succeeded (with openMP). After a bit googling, it seems that during the run time, the openMP library cannot be located. Can you add your openMP lib to the environment and check if it works?

**Comment by steven-murray** [comment]
@Kai-FengChen did @qyx268 's comment resolve your issue?

**Comment by qyx268** [comment]
seems like the problem's solved. closing
