### ISSUE TITLE
'Coeval'/'LightCone' object has no attribute 'get_cached_data'

### ISSUE THREAD

**Issue by catamorales** [21cmfast/21cmFAST#218]
Hi,
I have been trying to use the get_cached_data attribute for lightcones and for coeval objects. I checked the Accessing evolutionary Coeval data documents [https://21cmfast.readthedocs.io/en/latest/tutorials/gather_data.html?highlight=h5](url) and recreated the examples that are in there but I always get this error, also I tried it for the coeval and lightcones objects that I am running and it gives me the same error. I imported all the packages that are stated in that tutorial. 

This is the error showed when I run the example of the documents: 
`brightness_temp_z25 = coeval.get_cached_data(redshift=25.1, kind='brightness_temp', load_data=True)`
`AttributeError                            Traceback (most recent call last) 
<ipython-input-4-babb5fcbca66> in <module>
----> 1 brightness_temp_z25 = coeval.get_cached_data(redshift=25.1, kind='brightness_temp', load_data=True)
AttributeError: 'Coeval' object has no attribute 'get_cached_data'`

As for details, I am using:
* OS: macOS Big Sur 11.2.2
* Python version: 3.8.8
* Compiler version: JupyterLab 3.0.9
* Package versions: 21cmFast[3.0.3], h5py[2.10.0]

**Comment by BradGreig** [comment]
Hi @catamorales, I tried this by running from a script rather than a jupyter notebook and it worked for me (latest master). Are you able to try downloading and installing the most up to date version? (I don't see why this would be an issue as this feature came in prior to 3.0.3).

Are you able to provide a minimal working example?

If you place the following in a .py script and run it from your working environment (rather than with a jupyter notebook) it should reproduce the same behaviour as the tutorials. This may identify whether the issue is through ipython etc.

```
import matplotlib.pyplot as plt
import os

import py21cmfast as p21c

# For plotting the cubes, we use the plotting submodule:
from py21cmfast import plotting

# For interacting with the cache
from py21cmfast import cache_tools

import h5py
import numpy as np

if not os.path.exists('_cache'):
    os.mkdir('_cache')

p21c.config['direc'] = '_cache'
cache_tools.clear_cache(direc="_cache")

coeval = p21c.run_coeval(
    redshift = 25.0,
    user_params = {"HII_DIM": 30, "BOX_LEN": 30},
    flag_options={"USE_TS_FLUCT": True},
    random_seed=1978,
    write=True
)

brightness_temp_z25 = coeval.get_cached_data(redshift=25.1, kind='brightness_temp', load_data=True)

print(brightness_temp_z25)
```

**Comment by catamorales** [comment]
Hi @BradGreig , thank you for answering. I tried downloading the most up to date version of 21cmFast and got the 3.0.3 version again. I updated all the packages used within. Then I tried to run this example in the terminal using a .py script:

`import matplotlib`
`import matplotlib.pyplot as plt`
`import os`

`import py21cmfast as p21c`

`#For plotting the cubes, we use the plotting submodule:`
`from py21cmfast import plotting`

`# For interacting with the cache`
`from py21cmfast import cache_tools`

`import h5py`
`import numpy as np`
`if not os.path.exists('_cache'):`
    `os.mkdir('_cache')`
`p21c.config['direc'] = '_cache'`
`cache_tools.clear_cache(direc="_cache")`
`coeval = p21c.run_coeval(`
   ` redshift = 25.0,`
    `user_params = {"HII_DIM": 30, "BOX_LEN": 30},`
   ` flag_options={"USE_TS_FLUCT": True},`
   ` random_seed=1978,`
    `write=True`
`)`

`brightness_temp_z25 = coeval.get_cached_data(redshift=25.1, kind='brightness_temp', load_data=True)`

`print(brightness_temp_z25)`
And I got the same error: 
`Traceback (most recent call last):
  File "prueba.py", line 31, in <module>
    brightness_temp_z25 = coeval.get_cached_data(redshift=25.1, kind='brightness_temp', load_data=True)
AttributeError: 'Coeval' object has no attribute 'get_cached_data'`

<img width="1440" alt="Screen Shot 2021-03-17 at 15 04 35" src="https://user-images.githubusercontent.com/77252442/111541687-68bafa00-8736-11eb-9222-20d529252e52.png">

**Comment by steven-murray** [comment]
Hi Catalina,

Can you try installing with `pip install git+git://
github.com/21cmFAST/21cmFAST/`?

**Comment by BradGreig** [comment]
Hi @catamorales can you please try running `pip install git+git://github.com/21cmFAST/21cmFAST.git` from your conda environment. That should grab the most up to date version

**Comment by catamorales** [comment]
Hi @steven-murray and @BradGreig, thank you very much. With that I got the latest version and now the error doesn't shows up.

**Comment by steven-murray** [comment]
Looks like we have to release v3.1.0 soon :-)
