### ISSUE TITLE
[BUG] 2LPT has preferred direction

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#22]
**Describe the bug:**

I am unclear as to the precise nature of this bug -- @jaehongpark00 can you comment on this?

**Comment by jaehongpark00** [comment]
When using second-order Lagrangian perturbation theory (SECOND_ORDER_LPT_CORRECTIONS = 1), density fields are elongated a specific direction, i.e. high-density regions are always elongated to the y-axis.
