### ISSUE TITLE
[BUG] GSL error when using Power spectrum in a lightcone

### ISSUE THREAD

**Issue by catamorales** [21cmfast/21cmFAST#225]
**Describe the bug:**
I am trying to run the code below for a lightcone with `POWER_SPECTRUM`= 5, I tried the same for a coeval box and it worked. Also, I ran a lightcone and coeval objects but with streaming velocities, which sets `POWER_SPECTRUM`= 5 and it worked. I tried running it from Jupyter Lab and also using a .py document in the terminal. 

**To Reproduce:**
`import py21cmfast as p21c` 
`from py21cmfast import plotting` 
`from py21cmfast import cache_tools` 
`import os` 
`print(f"21cmFAST version is {p21c.__version__}")` 

`lightcone = p21c.run_lightcone(` 
    `redshift = 5.0,` 
    `max_redshift = 15.0,` 
    `user_params = {"HII_DIM":256, "BOX_LEN": 400, "DIM":768, "POWER_SPECTRUM":5 },` 
    `lightcone_quantities=("brightness_temp", 'density', 'xH_box'),` 
    `global_quantities=("brightness_temp", 'density', 'xH_box'),` 
    `flag_options = {"INHOMO_RECO" : True,},` 
   `random_seed = 12345,` 
    `direc = 'lightconesf')` 

**Error showed:**
When I run the code I get this error, I will just show the part of it because it is too much text, between this it shows the cosmo, astro, user parameters. 
`2021-04-16 10:48:46 | ERROR   | ps.c            | sigma_z0:444 [pid=1808/thr=0] | gsl integration error occured!`
`2021-04-16 10:48:46 | ERROR   | ps.c            | sigma_z0:445 [pid=1808/thr=0] | (function argument): lower_limit=1.000000e-05 upper_limit=3.774746e+01 rel_tol=1.000000e-06 result=4.997059e+08 error=6.342499e+02`
`2021-04-16 10:48:46 | ERROR   | ps.c            | sigma_z0:446 [pid=1808/thr=0] | data: M=1.313924e+14`
.....
`Traceback (most recent call last):`
  `File "lps.py", line 9, in <module>`
    `lightcone = p21c.run_lightcone(`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/wrapper.py", line 2753, in run_lightcone`
    `ib2 = ionize_box(`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/wrapper.py", line 1637, in ionize_box`
    `return box.compute(`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/_utils.py", line 1034, in compute`
    `_process_exitcode(exitcode, self._c_compute_function, args)`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/_utils.py", line 116, in _process_exitcode`
   `raise {`
`py21cmfast._utils.GSLError: A GSL routine has errored! (check the LOG for more info)`

**Details:**
 - OS: macOS Big Sur 11.2.3
 - Python Version: 3.8.8
 - Relevant compiler versions: Jupyter lab: 3.0.9, GSL: 2.4
 - Relevant package versions: 21cmFAST version is 3.0.4.dev228+gec274c2

**Comment by qyx268** [comment]
hmm... I can't reproduce this on linux (nefertem). I will try on my Mac then.

**Comment by BradGreig** [comment]
Hi @catamorales, thanks for providing the MWE. I think I have been able to reproduce your error. I'm not sure why it fails in some cases while works in others like you have found. Seems a little odd to me, but maybe there are slight differences.

It appears the GSL integration routine isn't able to achieve the desired accuracy and thus is throwing up an error. I have created a new branch ([catamorales-issue](https://github.com/21cmfast/21cmFAST/tree/catamorales-issue)) with a possible fix. Could you please try switching to that branch and running the same piece of code. The change I have made resolved the error on my end.

Let me know if that works or not.

**Comment by catamorales** [comment]
Thank you @BradGreig. I switched to the new branch but it continues to show the GSL error, I tried to run some models using global parameters (cutoff, mwdm and g_x) and happened the same. I am not sure if the problema is related to using power spectrum by itself without streaming velocities. 
`2021-04-19 10:43:31 | ERROR   | ps.c            | sigma_z0:444 [pid=4121/thr=0] | gsl integration error occured!`
`2021-04-19 10:43:31 | ERROR   | ps.c            | sigma_z0:445 [pid=4121/thr=0] | (function argument): lower_limit=1.000000e-`05 upper_limit=3.774746e+01 rel_tol=1.000000e-06 result=4.997059e+08 error=6.342499e+02`
`2021-04-19 10:43:31 | ERROR   | ps.c            | sigma_z0:446 [pid=4121/thr=0] | data: M=1.313924e+14`
`2021-04-19 10:43:31,567 | ERROR | _utils.py::_process_exitcode() | In function: ComputeIonizedBox.  Arguments:`
...
`Traceback (most recent call last):`
  `File "lps.py", line 8, in <module>
    lightcone = p21c.run_lightcone(`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/wrapper.py", line 2753, in run_lightcone`
    `ib2 = ionize_box(`
 ` File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/wrapper.py", line 1637, in ionize_box`
   ` return box.compute(`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/_utils.py", line 1034, in compute
    _process_exitcode(exitcode, self._c_compute_function, args)`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/_utils.py", line 116, in _process_exitcode
    raise {`
`py21cmfast._utils.GSLError: A GSL routine has errored! (check the LOG for more info)`
Also, this is what I used to switch to the branch, after that I used git pull and it told that everything is up to date.
`(myenv) catalinamorales@Catalinas-MacBook-Pro 21cmFAST % git checkout -t remotes/origin/catamorales-issue`
`Branch 'catamorales-issue' set up to track remote branch 'catamorales-issue' from 'origin'.`
`Switched to a new branch 'catamorales-issue'`

**Comment by catamorales** [comment]
Hi @BradGreig first of all thank you very much for your help, that worked and know everything runs without any errors. Second of all, I am really sorry, the first time I didn't compiled the correct branch, my bad.

**Comment by steven-murray** [comment]
I cannot count the number of times I have done that!

**Comment by BradGreig** [comment]
Hi @catamorales, no problems. As @steven-murray said, we all (and still) do it!

It actually made me identify the GSL error reporting functionality. Which I am now going to go add into the code to improve the overall error reporting with respect to providing additional contextual information. So all good!

**Comment by catamorales** [comment]
Hi, 
I am reopening this issue because the error is showing again but in different cases. Now it is happening when I run a code with global parameters, using mWDM >= 2.8 keV. I tried with mWDM=2.1 keV and worked.
To reproduce: 
`import os`
`import logging, sys, os`
`logger = logging.getLogger('21cmFAST')`
`logger.setLevel(logging.INFO)`
`import py21cmfast as p21c`
`from py21cmfast import plotting`
`from py21cmfast import cache_tools`
`from py21cmfast import global_params`

`with global_params.use(P_CUTOFF= True, M_WDM=3.0 , g_x=1.5):`
   ` coeval5nueve = p21c.run_coeval(`
       ` redshift = 5.9,`
        `user_params = {"HII_DIM": 256, "BOX_LEN": 400,  "DIM":768, "POWER_SPECTRUM":5  },`
        `flag_options = {"INHOMO_RECO": True,},`
        `random_seed=12345,`
        `direc = '_cachewdm3'`
    `)`

Error showed: 
When I run the code I get this error, I will just show the part of it because it is too much text, between this it shows the cosmo, astro, user parameters. I checked if I was using the GSL_INTEG_GAUSS61, because of @BradGreig told me about it last time and I am, and it worked for the past situations. I tried to find with my advisor where GSL_INTEG_GAUSS61 is in the code, because we didn’t want to bother, but we couldn’t find it.
`2021-04-29 22:28:11 | ERROR   | ps.c            | sigma_z0:444 [pid=13898/thr=0] | gsl integration error occured!`
`2021-04-29 22:28:11 | ERROR   | ps.c            | sigma_z0:445 [pid=13898/thr=0] | (function argument): lower_limit=1.000000e-05 upper_limit=8.581217e+01 rel_tol=1.000000e-06 result=1.293919e+09 error=1.411529e+03`
`2021-04-29 22:28:11 | ERROR   | ps.c            | sigma_z0:446 [pid=13898/thr=0] | data: M=1.118373e+13`
`2021-04-29 22:28:11,102 | ERROR | In function: ComputeIonizedBox.  Arguments:`
…
`Traceback (most recent call last):`
  `File "coevalwdmmpy.py", line 33, in <module>`
    `coeval5nueve = p21c.run_coeval(`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/wrapper.py", line 2344, in run_coeval`
    `ib2 = ionize_box(`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/wrapper.py", line 1637, in ionize_box`
    `return box.compute(`
  `File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/_utils.py", line 1034, in compute`
   ` _process_exitcode(exitcode, self._c_compute_function, args)`
 ` File "/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/_utils.py", line 116, in 
_process_exitcode`
   ` raise {`
`py21cmfast._utils.GSLError: A GSL routine has errored! (check the LOG for more info)`
Details:
* OS: macOS Big Sur 11.2.3
* Python Version: 3.8.8
* Using 21cmFAST version 3.0.4.dev228+gec274c2

**Comment by BradGreig** [comment]
Hi @catamorales, I just tried running this and it worked without issue for me. This seems a little odd to me, especially given it resolved your previous issue.

One thing that stands out to me is that the reported error is missing a piece of output that I added with the fix. So I am not entirely sure if you do have the correct version compiled. Remember, the code needs to be compiled again. Please make sure you are on the master branch (or have pulled in master into your own branch if you have one) and then compile again. The piece of code missing contains an additional argument which gives more detail to the GSL error (it should say "roundoff error" if it was for the same problem.

To find the usage of `GSL_INTEG_GAUSS61` that I was referring to, navigate to `/Users/catalinamorales/anaconda3/envs/myenv/lib/python3.8/site-packages/py21cmfast/src/py21cmfast/src` and open `ps.c` and search for the function sigma_z0. The integration routine `gsl_integration_qag` will have the argument.

Let me know how you get along.

**Comment by catamorales** [comment]
Hi @BradGreig, I realized that I was on the catamoraees-issue branch, so I did what you said and now everything works fine. Thank you very much.

**Comment by BradGreig** [comment]
Hi @catamorales, no problems. Glad to hear it is all working!
