### ISSUE TITLE
[Question] How to determine parameters of a lightcone already saved to disk?

### ISSUE THREAD

**Issue by parphyam** [21cmfast/21cmFAST#240]
**Describe what you would like to do**

From a pre-constructed lightcone (made with 21cmFAST), can we determine the parameters used? 
**What I've tried**

`import h5py`
`data = h5py.File('LightCone_z7.0_b52d148327d356529e10d6b6523ebf43_r189387462315.h5')`
`cosmo = np.asarray(data['cosmo_params'])`
This returns the output` []`. How to know what parameters have been used?

**Comment by steven-murray** [comment]
Hi @parphyam,

I think the easiest way of doing this would be:

```python
from py21cmfast import LightCone
lc = LightCone.read('LightCone_z7.0_b52d148327d356529e10d6b6523ebf43_r189387462315.h5')
print(lc.cosmo_params)
```

**Comment by parphyam** [comment]
Hi @steven-murray ,
Thanks for the response, and your method does work. But since this is a HDF5 file, shouldn't it work with the `h5py` module, returning the parameters one is looking for instead of returning a blank array/list? If you can kindly look into this, it would enable analysis the contents of the lightcone in any system (with or without 21cmFAST installed).

**Comment by steven-murray** [comment]
Hi @parphyam, this is a good idea. I have made a new issue #241 to document the internal structure of these files.
