### ISSUE TITLE
[URGENT] are we missing all write=write in the functions?

### ISSUE THREAD

**Issue by qyx268** [21cmfast/21cmFAST#244]
**Describe the bug:**

Hmm... before I start implementing this, can I just double check with you guys? Are we missing `write=write` in functions called in `run_lightcone` and `run_coeval`? I'm not sure if the `hooks` argument contains such an information. But it looks like when I run MCMC (more specifically with MultiNest) using the current master branch, I keep getting new h5 files after initialization.... But after I manually put `write=write` back, I don't get new h5 files.

**To Reproduce:**
1. do a MCMC 
2. or just do a run_lightcone with `write=False` to see if you still get output (I haven't tried this yet though)

**Comment by steven-murray** [comment]
@qyx268 No, these are not missing -- the `hooks` argument contains this info. So you should be able to just do `write=False` in `run_coeval`, then that gets put into the `hooks` dict. Not sure if 21cmMC is going to play nicely with this yet, though!
