### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Mdlalose** [21cmfast/21cmFAST#248]
Greetings 21cmFAST developers, I have installed 21cmFast via conda, and it did install successfully without any errors. Now, when I import py21cmFAST, its gives  a warning error message that says " /home/mmdlalose/anaconda3/lib/python3.8/site-packages/py21cmfast/_cfg.py:32: UserWarning: Your configuration file is out of date. Updating...   warnings.warn("Your configuration file is out of date. Updating...")", and when I run run_coeval following tutorial, I get this error "  Found no user data directory for 21cmFAST! Should be at /home/mthokozisi/.21cmfast.Try re-installing 21cmFAST."  Please can help resolve these issues. Thanks, Regards, Mthokozisi

**Comment by steven-murray** [comment]
Hi @Mdlalose -- this is an error that existed in 21cmFAST v3.0.3. 

Please install v3.1.1 with `conda install -c conda-forge 21cmFAST=3.1.1`, and this issue will go away.

For the future, please put your question into the comment box rather than the title! :-)

**Comment by Mdlalose** [comment]
Thanks for your response.

**Comment by steven-murray** [comment]
No problem! All the best.
