### ISSUE TITLE
[Feature Req.] Return all functionality of original 21cmFAST 

### ISSUE THREAD

**Issue by BradGreig** [21cmfast/21cmFAST#25]
**Is your feature request related to a problem? Please describe.**

The current version is based on the 21CMMC version of the streamlined 21cmFAST. There is no support for explicitly using haloes, which is a feature of 21cmFAST.

**Describe the solution you'd like**

Must migrate over all the original functionality of 21cmFAST into this version of 21cmFAST.

**Comment by steven-murray** [comment]
Can we try to break this up into individual issues? Then we can attack them in parallel. We can also prioritize those issues that will be API-breaking.
