### ISSUE TITLE
stepping over array in determine_deltaz_for_photoncons

### ISSUE THREAD

**Issue by qyx268** [21cmfast/21cmFAST#253]
**Describe the bug:**

Looks like a memory issue. The bug comes from the following part in `determine_deltaz_for_photoncons`,

```
            while(val2 < val1 && (counter < 75 || (1+(i+1)+counter) > (N_NFsamples+N_extrapolated))) {
                counter += 1;
                if ((i+counter) > (N_NFsamples+N_extrapolated)){
                    LOG_ERROR("Stepping over! i=%d; counter=%d; N_NFsamples=%d; N_extrapolated=%d.", i, counter,N_NFsamples, N_extrapolated);
                    Throw(PhotonConsError);
                }
                val2 = deltaz[i+1+counter];

                deltaz_smoothed[i+1] = ( val1 + deltaz[1+(i+1)+counter] )/2.;
            }

```
where the LOG_ERROR is newly added for debugging. With the parameters below, it shows 
`2021-07-30 15:55:35 | ERROR   | ps.c            | determine_deltaz_for_photoncons:3885 [pid=2496320/thr=0] | Stepping over! i=24; counter=77; N_NFsamples=100; N_extrapolated=0.`
This means that `deltaz[i+1+counter]` is calling `deltaz[102]` while `deltaz` has only `N_NFsamples + N_extrapolated + 1 = 101` elements, unless I missed redefining of N_NFsamples or N_extrapolated.

**To Reproduce:**

This parameter set should show the problem:
```
import py21cmfast as p21c
import numpy as np

user_params = p21c.UserParams(BOX_LEN=50.0, DIM=75, HII_DIM=25, 
                              PERTURB_ON_HIGH_RES=True,USE_INTERPOLATION_TABLES=True)

astro_params = p21c.AstroParams(ALPHA_ESC=-0.9339440762996674, ALPHA_STAR=0.8675894141197205, 
                                F_ESC10=np.log10(0.01145147356426178), F_STAR10=np.log10(0.033935777056378895), 
                                M_TURN=np.log10(155267631.37657174),t_STAR=0.6399314802885055)

flag_options = p21c.FlagOptions(EVOLVING_R_BUBBLE_MAX=True, INHOMO_RECO=True,
                                PHOTON_CONS=True, USE_MASS_DEPENDENT_ZETA=True)

p21c.global_params.PhotonConsEndCalibz = 4.0

lc = p21c.run_lightcone(redshift=4.9, max_redshift=15, user_params=user_params,
                         astro_params=astro_params, flag_options=flag_options, direc='./test/')
```

**Expected behavior:**

This was found while running py21cmmc with photon conservation and down to z=4.9. By restarting ~2-3 times after crash, py21cmmc seems to be running smoothly now (i.e. no more crashes). So I suspect that the parameter sets that were causing the problem are likely to be extreme models with weird features in the corner of the parameter space that the PC algorithm was not built to capture. So one can always just continuing sampling after the code crashes to "solve" the problem. But it's annoying. 
With the added Throw(PhotonConsError) line, one can skip these models in py21cmmc with try and exception. So perhaps, it's not a big deal unless we get time to look further into this.

**Details:**
homePC (ubuntu), also trantor
python 3

**Additional context**

Run with the current master will not show the issue. You have to add the `if` check. This means that when running with PC, most py21cmfast models might simply get lucky to survive in py21cmmc with only a few being captured and crashing the inference.

**Comment by steven-murray** [comment]
Thanks for the report, @qyx268. If we want to actually *fix* this, then @BradGreig will have to weigh in. 

I think the idea of throwing a PhotonCons error, and propagating that error up through 21cmMC (and ignoring it in the sampler, just throwing a warning) is a great way to go.

**Comment by steven-murray** [comment]
@qyx268 thinks this is solved!
