### ISSUE TITLE
Design Philosophy Docs Outdated

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#262]
The design philosophy docs mention that a config file is "automatically created" on installation. This is now wrong -- by default no file is created, and the config is defined inside the code itself (but can be written to file). The reason for this is because the default config location isn't writable on CI.

**Comment by ChenxiSSS** [comment]
Yeah, I was looking for the config file when I just started to use 21cmFAST a couple of days ago. Was confused at first, later write a config file on my own.
Also, when I check the example config file in the doc, there is no such file. Might need to fix that also?
https://21cmfast.readthedocs.io/en/latest/user_data/runconfig_example.yml
