### ISSUE TITLE
[BUG] 'max_redshift' parameter not effective in run_lightcone for version 3.1.4.dev

### ISSUE THREAD

**Issue by bohuarolandli** [21cmfast/21cmFAST#265]
**Describe the bug:**
The 'max_redshift' parameter passed to the 'run_lightcone' function is not really effective. In other words, it does not really set the maximum redshift of a lightcone but seems futile. In fact, lightcone runs actually use 'Z_HEAT_MAX' in the global parameters.

**Details:**
 - Relevant package versions: 21cmfast v3.1.4.dev

**Comment by steven-murray** [comment]
Hi @bohuarolandli -- just to make sure we're on the same page: it is intended that the `max_redshift` parameter only specifies the maximum redshift contained in the *output lightcone*, not the maximum redshift that is evaluated for the lightcone integral. Is this the behaviour you are seeing?

**Comment by bohuarolandli** [comment]
> Hi @bohuarolandli -- just to make sure we're on the same page: it is intended that the `max_redshift` parameter only specifies the maximum redshift contained in the _output lightcone_, not the maximum redshift that is evaluated for the lightcone integral. Is this the behaviour you are seeing?

No, I checked that the output is also tailored by `Z_HEAT_MAX`, such as the attributes that start with `lightcone_`. The dimension agrees with those of the lightcone data boxes. So the redshift range of all the output seems to be determined by `Z_HEAT_MAX` rather than `max_redshift`.

**Comment by BradGreig** [comment]
Hi @bohuarolandli, if I can just chip in quickly. The usage of `max_redshift` is dependent specifically on what you are attempting to do. In some sense, it is conditional.

If you have either of `INHOMO_RECO` or `USE_TS_FLUCT` set to `True`, the maximum redshift of the light-cone will default to `Z_HEAT_MAX`. The reason for this is that for either of these, the code is performing many more computations, so we try and avoid doing additional computations. In this case, `Z_HEAT_MAX` is the maximum redshift for which we are computing the corresponding physics. Increasing `Z_HEAT_MAX` will increase the maximum redshift of the lightcone, but in doing so you have to be careful that the physics is still being computed properly.

If both `INHOMO_RECO` and `USE_TS_FLUCT` are set to `False`, then the maximum redshift of the lightcone will be set by `max_redshift`.

There are quite a few combinations of options which has likely led to a bit of divergence in the functionality certain parameters. Hope that somewhat helps in what you are using the code for.

**Comment by bohuarolandli** [comment]
Hi @BradGreig, thank a lot for your explanation! That answers my question. @steven-murray Thank you both for prompt responses! I will close the issue.
