### ISSUE TITLE
[Feature Req.] Matplotlib Error (version > 3.3) while producing sliceplots of Tb and lightcones

### ISSUE THREAD

**Issue by SuvedhaNaik** [21cmfast/21cmFAST#266]
**Is your feature request related to a problem? Please describe.**

_[21cmFAST v3.1.3, python v3.10, matplotlib v3.5]_
Running the tutorial codes to make `sliceplots` for differential brightness temperature (and `lightcones`) produces the following error related to the usage of `imshow()`:

> ValueError: Passing parameters norm and vmin/vamx simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it. 

The error seems to have arisen due to the matplotlib version v>3.3.

**Describe the solution you'd like**

One may have to pass the arguments suitably for the latest matplotlib version and make necessary modifications in multiple parts of the code.

Running the same piece of code with matplotlib version 3.3 gave the following warning:

> Matplotlib Deprecation Warning: Passing parameters norm and vmin/vmax simultaneously is deprecated since 3.3 and will become an error two minor releases later. Please pass vmin/vmax directly to the norm when creating it.

**Describe alternatives you've considered**

Created conda environment with python v3.9 
Installed 21cmFAST (v3.1.3) using 
`conda install -c conda-forge 21cmFAST=3.1.3`
(I had to install h5py explicitly by running `conda install h5py`)

This way, I had matplotlib version 3.3, and I could run the codes mentioned above without any errors.

**Comment by steven-murray** [comment]
Thanks @SuvedhaNaik! This sounds like something easy to fix. Hopefully someone can get to it soon.

**Comment by steven-murray** [comment]
Closing this as resolved in v3.1.4
