### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AgusTor92** [21cmfast/21cmFAST#274]
Hello, I'm new to using the package 21cmFAST with conda . I have problems with running a small code after installing 21cmFAST. i run the small code given in the description:

import py21cmfast as p21c
coeval = p21c.run_coeval(
    redshift=8.0,
    user_params={'HII_DIM': 50, "USE_INTERPOLATION_TABLES": False}
)
p21c.plotting.coeval_sliceplot(coeval, kind='brightness_temp')

**Describe the bug:**
and I got the following message:

OSError: Found no user data directory for 21cmFAST! Should be at /Users/feynman/.21cmfast.Try re-installing 21cmFAST. 

**To Reproduce:**
1. ...
2. ...

**Expected behavior:**

**Details:**
 - OS: MacOS Monterey
 - Python Version: 3.9

**Additional context**
I reinstall 21cmFAST again and again but I got the same message. Can you give me a hand? 
Thanks

**Comment by steven-murray** [comment]
Hi @AgusTor92 -- can you print out the result of `conda list | grep 21cmFAST`?

**Comment by AgusTor92** [comment]
After typing conda list i got the following

21cmfast                  3.1.1            py39hffa0f39_0    conda-forge
appnope                   0.1.2           py39hecd8cb5_1001  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39hca72f7f_0  
astropy                   5.0              py39h7588534_0  
attrs                     21.4.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
basemap-data              1.3.2              pyhd3eb1b0_1  
basemap-data-hires        1.3.2              pyhd3eb1b0_1  
bidict                    0.21.2             pyhd3eb1b0_0  
bleach                    4.1.0              pyhd3eb1b0_0  
brotli                    1.0.9                hb1e8313_2  
c-ares                    1.18.1               hca72f7f_0  
ca-certificates           2022.2.1             hecd8cb5_0  
cached-property           1.5.2                      py_0  
certifi                   2021.10.8        py39hecd8cb5_2  
cffi                      1.15.0           py39hc55c11b_1  
click                     8.0.4            py39hecd8cb5_0  
cycler                    0.11.0             pyhd3eb1b0_0  
debugpy                   1.5.1            py39he9d5cce_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
descartes                 1.1.0              pyhd3eb1b0_4  
entrypoints               0.3              py39hecd8cb5_0  
fast-histogram            0.9              py39he3068b8_0  
fftw                      3.3.10          nompi_hf082fe4_102    conda-forge
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.11.0               hd8bbffd_0  
giflib                    5.2.1                haf1e3a3_0  
gsl                       2.6                  h71c5fe9_2    conda-forge
h5py                      3.6.0            py39h4a1dd59_0  
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
icu                       58.2                 h0a44026_3  
importlib-metadata        4.8.2            py39hecd8cb5_0  
importlib_metadata        4.8.2                hd3eb1b0_0  
ipykernel                 6.4.1            py39hecd8cb5_1  
ipympl                    0.8.7              pyhd3eb1b0_0  
ipython                   7.31.1           py39hecd8cb5_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
jedi                      0.18.1           py39hecd8cb5_1  
jinja2                    3.0.2              pyhd3eb1b0_0  
jpeg                      9d                   h9ed2024_0  
jsonschema                3.2.0              pyhd3eb1b0_2  
jupyter                   1.0.0            py39hecd8cb5_7  
jupyter_client            7.1.2              pyhd3eb1b0_0  
jupyter_console           6.4.0              pyhd3eb1b0_0  
jupyter_core              4.9.1            py39hecd8cb5_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
kiwisolver                1.3.2            py39he9d5cce_0  
krb5                      1.19.2               hcd88c3b_0  
lcms2                     2.12                 hf1fd2bf_0  
libblas                   3.9.0           1_h508aa58_netlib    conda-forge
libcblas                  3.9.0           5_h0661a58_netlib    conda-forge
libcurl                   7.80.0               h6dfd666_0  
libcxx                    12.0.0               h2f01273_0  
libedit                   3.1.20210910         hca72f7f_0  
libev                     4.33                 h9ed2024_1  
libffi                    3.3                  hb1e8313_2  
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
liblapack                 3.9.0           5_h0661a58_netlib    conda-forge
libnghttp2                1.46.0               ha29bfda_0  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.18               h1de35cc_0  
libssh2                   1.9.0                ha12b0ac_1  
libtiff                   4.2.0                h87d7836_0  
libwebp                   1.2.2                h56c3ce4_0  
libwebp-base              1.2.2                hca72f7f_0  
llvm-openmp               12.0.0               h0dcd299_1  
lz4-c                     1.9.3                h23ab428_1  
markupsafe                2.0.1            py39h9ed2024_0  
matplotlib                3.5.1            py39h6e9494a_0    conda-forge
matplotlib-base           3.5.1            py39hfb0c5b7_0  
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mistune                   0.8.4           py39h9ed2024_1000  
mpl-scatter-density       0.7                        py_0  
mpld3                     0.5.7              pyhd3eb1b0_0  
munkres                   1.1.4                      py_0  
nbclient                  0.5.11             pyhd3eb1b0_0  
nbconvert                 6.3.0            py39hecd8cb5_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.3                  hca72f7f_2  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
nomkl                     1.0                  h5ca1d4c_0    conda-forge
notebook                  6.4.8            py39hecd8cb5_0  
numpy                     1.22.2           py39h9d9ce41_0    conda-forge
olefile                   0.46               pyhd3eb1b0_0  
openssl                   1.1.1m               hca72f7f_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.2.4            py39h23ab428_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.4.0            py39h98e4679_0  
pip                       21.2.4           py39hecd8cb5_0  
prometheus_client         0.13.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
prompt_toolkit            3.0.20               hd3eb1b0_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pycparser                 2.21               pyhd3eb1b0_0  
pyerfa                    2.0.0            py39h9ed2024_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyqt                      5.9.2            py39h23ab428_6  
pyrsistent                0.18.0           py39hca72f7f_0  
python                    3.9.7                h88f2d9e_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd3eb1b0_0  
pyyaml                    6.0              py39hca72f7f_1  
pyzmq                     22.3.0           py39he9d5cce_2  
qt                        5.9.7                h468cd18_1  
qtconsole                 5.2.2              pyhd3eb1b0_0  
qtpy                      1.11.2             pyhd3eb1b0_0  
readline                  8.1.2                hca72f7f_1  
scipy                     1.8.0            py39h056f1c0_1    conda-forge
seaborn                   0.11.0                     py_0  
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                58.0.4           py39hecd8cb5_0  
sip                       4.19.13          py39h23ab428_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.37.2               h707629a_0  
terminado                 0.13.1           py39hecd8cb5_0  
testpath                  0.5.0              pyhd3eb1b0_0  
tk                        8.6.11               h7bc2e8c_0  
tornado                   6.1              py39h9ed2024_0  
traitlets                 5.1.1              pyhd3eb1b0_0  
typing-extensions         3.10.0.2             hd3eb1b0_0  
typing_extensions         3.10.0.2           pyh06a4308_0  
tzdata                    2021e                hda174b7_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39hecd8cb5_1  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2            py39hecd8cb5_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                haf1e3a3_0  
zeromq                    4.3.4                h23ab428_0  
zipp                      3.7.0              pyhd3eb1b0_0  
zlib                      1.2.11               h4dc903c_4  
zstd                      1.4.9                h322a384_0

**Comment by AgusTor92** [comment]
However @steven-murray , I will try to fix this by using the recommendation given in #266

**Comment by AgusTor92** [comment]
Great @steven-murray. Sorry for the inconveniences. I was following all the issues and discussions and I got stuck. I will update 21cmFAST and pray for a successful running.

**Comment by AgusTor92** [comment]
Okay, it works! Thanks, @steven-murray  -- I run some examples to get in touch with the code.  In some examples, the kernel has died but it can be fixed.
