### ISSUE TITLE
[BUG] unexpected behaviour for `write=False`

### ISSUE THREAD

**Issue by dprelogo** [21cmfast/21cmFAST#277]
**Describe the bug:**
When calling `p21.run_lightcone` with `write = False`, it still caches all the files. The same probably holds for all underlying functions.

**Expected behavior:**
Even with the new flexibility of the `write` flag, I assume making it `False` should turn off all caching/writing.

**Comment by steven-murray** [comment]
Huh, that is surprising. I'll have a look into it.

**Comment by qyx268** [comment]
I had this issue before. @dprelogo  can you confirm if you have cache_dir set to some value? If so, _get_config_options in py21cmfast will reset write=True. 

@steven-murray perhaps this was done on purpose?

**Comment by qyx268** [comment]
okay, even with `cache_dir=None`, the program still outputs files into the default cache folder...

**Comment by steven-murray** [comment]
OK something definitely seems wrong here. Unfortunately I don't have time to look at it right now. Maybe by the end of the week. Certainly when setting `write=False` you should expect that nothing is written out at all. But this now goes through the `hooks` so it is a little more complex than just simply "not writing".

**Comment by charlottenosam** [comment]
FYI @qyx268 I've been having the same problem. The only thing that seems to work for me is also setting the config variable 
`p21c.config['write'] = False`
