### ISSUE TITLE
[Feature Req.] Standard Colour Map for Lightcones

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#28]
**Is your feature request related to a problem? Please describe.**

Not a problem, but I like the standard colour map.

**Describe the solution you'd like**

Add the standard colour map (matlab standard)

**Describe alternatives you've considered**

**Additional context**

**Comment by NGillet** [comment]
### LC color from Brad and Andrei
    EoR_colour = matplotlib.colors.LinearSegmentedColormap.from_list('EoR_colour',
                                                                     [(0, 'white'),
                                                                      (0.21, 'yellow'),
                                                                      (0.42, 'orange'),
                                                                      (0.63, 'red'),
                                                                      (0.86, 'black'),
                                                                      (0.9, 'blue'),
                                                                      (1, 'cyan')])
    plt.register_cmap(cmap=EoR_colour)
    plt.rcParams['image.cmap'] = 'EoR_colour'

**Comment by steven-murray** [comment]
nice. I can put that in maybe tomorrow.
