### ISSUE TITLE
[Feature Req.] Add in the ability to return the analytic reionisation history to Python

### ISSUE THREAD

**Issue by BradGreig** [21cmfast/21cmFAST#30]
**Is your feature request related to a problem? Please describe.**
It'll be handy to be able to access just the analytic reionisation history. In that way it could be callable by 21CMMC.

**Describe the solution you'd like**
A Python function which returns the analytic reionisation history

**Comment by steven-murray** [comment]
Is this already a standalone C function?

**Comment by BradGreig** [comment]
It is a stand alone C function, but its not callable by Python. Basically, it just needs to be wrapped to have the output accessible by Python. Its trivial, but something that should be done

**Comment by BradGreig** [comment]
Resolved with #24
