### ISSUE TITLE
Estimating Evidence using MultiNest sampler

### ISSUE THREAD

**Issue by SuvedhaNaik** [21cmfast/21cmFAST#381]
Hello, 

I want to use 21CMMC to compare different models against some data sets. 
I want to perform a Bayesian model comparison to do so. 
Since 21CMMC already has the `MultiNest` sampler, 
is there a way to get the Bayesian evidence of the model? 

Thanks in advance.

Suvedha

**Comment by qyx268** [comment]
The evidence should be in the MultiNest output, i.e. `datadir`/Multinest/`model_name`stats.dat
