### ISSUE TITLE
[Feature Req.] Create more than just brightness_temp lightcones

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#39]
**Is your feature request related to a problem? Please describe.**

Currently, the `run_lightcone` function only creates a lightcone out of the brightness temperature. 
While this is usually what people want, one may also want to see a lightcone of `xHI` or even the density field. 

**Describe the solution you'd like**

The easiest solution is probably just to specify some reasonable outputs in the lightcone function, and add them to the `Lightcone`.

**Describe alternatives you've considered**

One could also try specifying exact a list of boxes to save in the lightcone, but this would be a bit brittle because it would be difficult to ascertain which structure they come from. Also, it would mean the `Lightcone` object would not be absolutely defined.

**Comment by BradGreig** [comment]
One simple option would be for run_lightcone to take additional arguments (for example flags) which specify if additional lightcones are desired. Then, these lightcones can be passed if required or NULL if the option is not chosen.

**Comment by qyx268** [comment]
How's the development of this? Is there anything I could help?

@andreimesinger and I are trying to calculate Lyman-alpha forest statistics, which requires lightcones of density, photoionization rate and the redshift of reionization.

**Comment by steven-murray** [comment]
AFAIK no-one has started this. What would your opinion be on an API for this (also, @andreimesinger)? I tried to outline two cases: one in which the `run_lightcone` function just internally sets some parameters into the `Lightcone` object, so for example as it runs, it computes `density` lightcone, and then at the end, saves this lightcone to the `Lightcone` object as well as the brightness temperature. 

Another option (which @BradGreig has endorsed) is to add keyword arguments to the function to turn on/off different pre-defined lightcone boxes. This has some added flexibility, but the downside that the `Lightcone` object at the end may have some attributes being `None` (so it's no longer a homogeneous object). 

The final option is to have a keyword to the function that accepts a list of field names which are supposed to be "lightconified", and anything in this list is added to the Lightcone. This is even more flexible, but means the Lightcone object itself is even less well-defined, unless we also define it in a similarly loose way. The other con here is that we have to decide on how to resolve the field names. Say someone puts in "density" -- we have to have a way of knowing where this fieldname comes from (`init_box`, `perturb_field`, etc.). Also, we'd have to be careful of name clashes between them (I don't think that's a problem yet though). 

Overall, I think I'd cast my vote for option (3) -- it means less development in the future to add new things that people may want. We'll just have to be reasonably careful about how we deal with the `Lightcone` class. Any in disagreement? If there are no dissenters by my Thursday, I'll try to get cracking on this.

**Comment by BradGreig** [comment]
@steven-murray if we can pre-define all possible keyword arguments and have these clear in the documentation then I think your option (3) is probably the best solution (its just a cleverer implementation of my suggestion). Note that this change to the Lightcone class will have to be reflected in the Coeval class. As their behaviours should mimic one another. Further, this API change will potentially break existing peoples codes (e.g. @caw11). So again, should be a final change.

@qyx268 note that for constructing Lyman alpha forest spectra you'll also need gas temperature and peculiar velocities. Note, you'll need to be wary of comoving/proper coordinates as well. You might need to be careful when constructing them directly from lightcones as a result

**Comment by qyx268** [comment]
@BradGreig thx! I would definitely need your help later. The plan is to have a lightcone of z_ion as well... then use Mcquinn to evolve the temperature assuming the initial is some value (e.g 2e4K) when first ionized. I was gonna use GP approximation, but yes, peculiar velocity can also be included as long as I have a lightcone of it.

@steven-murray I root for option (3) as well. If you need to know the fields that I would be using, they are IonizedBox->Gamma12_box, IonizedBox->z_re_box, IonizedBox->dNrec_box, PerturbedField->density and PerturbedField->velocity.

**Comment by andreimesinger** [comment]
> On 03.12.2019., at 11:09, Yuxiang Qin <notifications@github.com> wrote:
> 
> @BradGreig <https://github.com/BradGreig> thx! I would definitely need your help later. The plan is to have a lightcone of z_ion as well... then use Mcquinn to evolve the temperature assuming the initial is some value (e.g 2e4K) when first ionized. I was gonna use GP approximation, but yes, peculiar velocity can also be included as long as I have a lightcone of it.
> 
i was originally thinking to just use the GP approximation, but thinking about it now, you have the v_z fields and one could adapt your framework for RSD in 21cm to compute the Lyman alpha e^-tau..  we do not need to integrate the full profile; just the resonant cross-section should be ok for the forest.

it would be great if you two can work on this while yuxiang is in melbourne, especially since this will be a large part of our contribution to the XQR-30 project!
> @steven-murray <https://github.com/steven-murray> I root for option (3) as well. If you need to know the fields that I would be using, they are IonizedBox->Gamma12_box, IonizedBox->z_re_box, IonizedBox->dNrec_box, PerturbedField-
> 
> >density and PerturbedField->velocity.
> 
> 

i am not sure i understand what is the difference between 2 and 3…

**Comment by steven-murray** [comment]
@andreimesinger (2) means that we the coders specify which quantities can be made into lightcones (and write them into the function call), and the user just has to set them as flags for which they actually want on any given run. (3) means the user can literally send any string fieldname in, and the function will try to find that field in one of the output structs (`init`, `perturb`, `ionization`, `spin_temp` or `brightness_temp`) and make a lightcone out of it. 

Looks like we have a push for (3). @BradGreig: I think in the case of (3), the documentation in `run_lightcone` should be fairly sparse, but point people to the documentation for each of the output objects. 
I agree, this could break people's code, so we should be careful about it, and let relevant people know exactly how to change their code when it is merged. 
In terms of the `Coeval` class -- I think that class already "basically" has this structure -- it now exposes the fieldnames of its structs. The difference for the lightcone is that it may not expose _all_ the fieldnames (to conserve memory).

**Comment by BradGreig** [comment]
@andreimesinger @qyx268 you already have access to the gas temperature from performing the spin temperature calculation. So in principle this could also be used for the temperature.

@steven-murray under the proposed format basically every quantity should in principle be accessible. For each output model this should be made clear what is available. However, I assume that people won't properly read all the documentation, thus, just having a list of all possible fieldnames for the lightcone/coeval classes somewhere would be useful.

Indeed memory usage will be an issue, not sure how best to treat this though

**Comment by andreimesinger** [comment]
> On 4 Dec 2019, at 01:35, BradGreig <notifications@github.com> wrote:
> 
> ﻿
> @andreimesinger @qyx268 you already have access to the gas temperature from performing the spin temperature calculation. So in principle this could also be used for the temperature.
> 
this is just the temperature in the neutral IGM, which is opaque in Lya in any case.  we are talking about the ionized IGM. in this case the code assumes a temperature of 10^4 K, but there are temperature inhomogeneaties we are missing, mainly from different reionization times and subsequent adiabatic cooling. 
> @steven-murray under the proposed format basically every quantity should in principle be accessible. For each output model this should be made clear what is available. However, I assume that people won't properly read all the documentation, thus, just having a list of all possible fieldnames for the lightcone/coeval classes somewhere would be useful.
> 
> Indeed memory usage will be an issue, not sure how best to treat this though
> 


agreed

**Comment by andreimesinger** [comment]
in that case, 3 sounds cleaner.  the main thing is to allow for additional fields in the future.

one thing to keep in mind is that lightcones for some fields are created with RSDs (the ones involving an optical depth), while for others no, so the code would have to treat, say density different from 21cm...

**Comment by BradGreig** [comment]
@andreimesinger ah, fair point. I guess my next question is to ask how trivial might be to include ionised temperature as well. Perhaps, quite complicated...

**Comment by andreimesinger** [comment]
i added a corresponding slack channel and we can move the discussion there…

in principle, one can add the temperature approximately just by using equation 6 from this:
https://arxiv.org/pdf/1512.00086.pdf <https://arxiv.org/pdf/1512.00086.pdf>

and using the z_in field to initialize the evolution, assuming an initial temperature of ~20k or something, and a corresponding density just linearly extrapolated to z_in…  so it is just evaluating this expression at every voxel in the z~5-6 lightcone
