### ISSUE TITLE
Place the FFTW wisdoms into a sensible central location

### ISSUE THREAD

**Issue by BradGreig** [21cmfast/21cmFAST#40]
**Is your feature request related to a problem? Please describe.**
Currently the FFTW wisdoms are written to the current working directory. This is less than ideal and they should be stored in some sensible central location.

**Describe the solution you'd like**
Save the FFTW wisdoms centrally

**Describe alternatives you've considered**

**Additional context**

**Comment by steven-murray** [comment]
I think it makes most sense to place them in the directory that holds the cached boxes, what do you think? We could do this by passing a string to the global params upon initialization (kind of like the external tables). 

This _may_ be inappropriate  if the user temporarily changes the global parameter. I'm not sure if there's a clean way of recognizing that change (the initialization is done at the original import). But we can think about that.

**Comment by BradGreig** [comment]
Yeah, to me it makes the most sense to place it in the cached boxes directory (or a subdirectory of that) and is what I was originally thinking.

**Comment by BradGreig** [comment]
@steven-murray to me this has been implemented has it not? If so, then this can be closed.

**Comment by steven-murray** [comment]
Yeah, you're right. They are saved in the `cache_dir/wisdoms/`
