### ISSUE TITLE
[BUG] NON_CUBIC_FACTOR

### ISSUE THREAD

**Issue by binnietom** [21cmfast/21cmFAST#403]
Hello, 
I think I found a bug on line 228 of BrightnessTemperatureBox.c.

It is currently "k_z = n_z * DELTA_K;" 
I think it should be "k_z = n_z * DELTA_K_PARA;"

If this is not the case please help me understand why!
Thanks,
Tom

**Comment by daviesje** [comment]
I think you're right, feel free to put up a PR if you'd like to do the fix yourself. Otherwise I'm happy to do it in a day or two
