### ISSUE TITLE
[Feature Req.] Remove default GSL error handling

### ISSUE THREAD

**Issue by BradGreig** [21cmfast/21cmFAST#41]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Replace the default GSL error handling with our own internal error handling to be able to output more constructive debugging results for any issue that may arise

**Describe alternatives you've considered**

**Additional context**

**Comment by steven-murray** [comment]
I almost tried doing this in #64 , but it was less obvious than I thought it might be. At first, I tried just replacing the global handler for GSL, so it could be done just once. But then I realised that the local contextual information in each function is kind of importan to print out. So I vote for treating every GSL call independently -- turning off the handling and handling it ourself.

**Comment by BradGreig** [comment]
Yeah, my original intention was for this to be done at each instance of GSL usage. In this way, we can output all the relevant information, inputs, functions etc. that were used that produced the error.

**Comment by BradGreig** [comment]
Hey @steven-murray this was implemented in #219 right? If you agree, I think this can be closed.

**Comment by steven-murray** [comment]
Yes indeed!
