### ISSUE TITLE
[Feature Req.] Ability to install FFTWf and GSL along with the library

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#45]
**Is your feature request related to a problem? Please describe.**

It can be quite annoying to have to manually install FFTW and GSL oneself, especially as the version of FFTW is probably only ever going to be used for 21cmFAST. It would be nice if these were installed automatically if not explicitly pointed to in installation. 

**Describe the solution you'd like**

Possibly the only realistic solution to this is to make fftwf a conda package, and have 21cmFAST installable via conda-forge. 

**Describe alternatives you've considered**

One could imagine having a sub-process in the setup.py manually installing the dependencies. However, I'd imagine that this would be fraught with danger given different OSes.

**Additional context**

I've been prompted by @acliu and @mirochaj about this.

**Comment by BradGreig** [comment]
Is this to be the default installation process or a optional installation option?

If its the former, this would force people to have to use conda etc. for 21cmFAST. I don't think this should be the case. If its instead an optional installation option, then this is fine.

**Comment by steven-murray** [comment]
*Definitely* optional.
