### ISSUE TITLE
[Feature Req.] Default should evaluate integrals exactly

### ISSUE THREAD

**Issue by BradGreig** [21cmfast/21cmFAST#46]
**Is your feature request related to a problem? Please describe.**
The default 21cmFAST should directly perform all integrals, with the existing use of interpolation tables being an additional option. 21CMMC should then turn on interpolation tables automatically

**Describe the solution you'd like**
Add yet another flag option to be able to switch between full integral evaluation and fast, approximate evaluation with interpolation tables

**Describe alternatives you've considered**

**Additional context**

**Comment by steven-murray** [comment]
This sounds like a good idea to me. It sounds like a v3.0.0 thing to me -- does that make sense to you?

**Comment by BradGreig** [comment]
Yep, definitely
