### ISSUE TITLE
[BUG] f_coll_min is not set

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#48]
At line 655 of `IonisationBox.c`, `f_coll_min` is used, but it is not set anywhere in the function.
I am also not sure what value it should take.

@BradGreig any idea what value this should take?

**Comment by BradGreig** [comment]
This is already an open issue (#33), and was already resolved in the PhotonCons branch prior to it being raised as an issue. As noted in #33 it'll be resolved once PhotonCons is merged

**Comment by steven-murray** [comment]
OK. I'm then going to vote that PhotonCons be merged. I'm going to create an issue to the effect that tests need to be added for the branch though.
