### ISSUE TITLE
Filter_box in UsefulFunctions.c produces segfault running under intel compiler [BUG]

### ISSUE THREAD

**Issue by catherinewatkinson** [21cmfast/21cmFAST#53]
In attempting to get the code to run on the HPC at Imperial, I experienced segfaults having compiled with the Intel ICC compiler.

The source of the segfault is the for loops in filter_box (UsefulFunctions.c), which take the form (L100):
(n_x=dimension; n_x--;)

Replacing this and the corresponding one for (n_y=dimension; n_y--;) with:
(n_x=(dimension-1);  n_x>=0; n_x--)

resolves the problem.

**Comment by BradGreig** [comment]
Weird, that is not the only place where I perform that kind of indexing for loops. In any case the multiprocessing branch resolves this as that too had issues with indexing in this manner.
