### ISSUE TITLE
[Feature Req.] A context manager for global params

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#60]
**Is your feature request related to a problem? Please describe.**

I've been thinking for a while about how to best manage the global params. Mostly it is pretty simple: just change a value of an attribute. However, for those used to using python, the concept of truly "global" parameters is a bit alien. You usually want to set parameters just for a given call, and not have them affect anything else. This could be kind of surprising for python users.

**Describe the solution you'd like**

One simple way could be to define a context manager on the global params class, which would enable something doing like this:

```python
with global_params.set(ALPHA_UVB=5.5):
    run_coeval(...)
```

After exiting from the context, the parameters are all set back to their default values. 

**Describe alternatives you've considered**

Another option would be to add keywords to each of the functions, which could change the global parameters _for that function_, and then remembers to set them back to their default value at the end. But that means changing a lot of code, so the context manager is to be preferred.

**Comment by BradGreig** [comment]
I think with this functionality this needs to be clearly documented. Also, presumably there will be instances where multiple hdf5 files will be output for different sets of global params. Are there internal checks to know which file corresponds to which set of global params? (i.e. if all other params are the same?)

**Comment by steven-murray** [comment]
Yeah, definitely will need to be documented. 

Yes, the hash produced in the filename of each HDF5 file _includes_ the global params, so that changing any global parameter make a unique file. In fact, at the moment, this goes a bit overboard, because not all global params are actually used in all the datasets, but there's no granularity in the global params. This harks back to #9 .
