### ISSUE TITLE
[BUG] No License!

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#7]
**Describe the bug:**

There is no license file included!
@andreimesinger can you decide on an appropriate license to include?

**Comment by andreimesinger** [comment]
sorry, i do not know anything about this...  are there standard options you recommend?

**Comment by steven-murray** [comment]
I usually use MIT -- it's permissive but allows people to make closed-source spin-offs if they want. GPLv3 is also widely used, and *doesn't* allow people to make closed-source spinoffs. But that can be a problem and some universities don't even allow employees to use that license for that reason. So I'd probably go with MIT unless you have a good reason not to.

**Comment by steven-murray** [comment]
Feel free to choose a different license, but otherwise you can just review/accept the PR.

**Comment by andreimesinger** [comment]
people have been making closed source spinoffs for 10 years...  i dont think this would stop them :-)

MIT sounds good then

**Comment by steven-murray** [comment]
Awesome, can you do a quick approval of the above PR, then this will be done.
