### ISSUE TITLE
Incorrectly FFTing unfiltered density field in first call to Wisdom in GenerateICs.c [BUG]

### ISSUE THREAD

**Issue by caw11** [21cmfast/21cmFAST#74]
I'm not 100% sure this is a bug, but it seems wrong to me that at L177 of GenerateICs.c which corresponds to the first call to wisdom, that the following operation occurs:
// copy over unfiltered box
memcpy(HIRES_box, HIRES_box_saved, sizeof(fftwf_complex)*KSPACE_NUM_PIXELS);

At L156 memcpy(HIRES_box_saved, HIRES_box, sizeof(fftwf_complex)*KSPACE_NUM_PIXELS); saves the unfilted k-space density field to the saved box.

I can only assume that this means that (under certain conditions) HIRES_box is being propagated forth unsmoothed which, to my understanding, is not the desired behaviour.

**Comment by steven-murray** [comment]
Is this the same as #36 ?

**Comment by caw11** [comment]
yes... sorry, I just checked if it was still the case in the current version. Will check old issues before posting in the future.

**Comment by steven-murray** [comment]
Excellent. I think this is getting fixed in #71 !
