### ISSUE TITLE
Installation issues (and how to resolve)

### ISSUE THREAD

**Issue by binnietom** [21cmfast/21cmFAST#75]
Hello, 
The conda environment '21CMMC' that is made during py21cmmc isntallation currently doesnt work for me - I've had a meal of a time trying to run it on imperial's HPC, but here is a solution:

The following instructions produces a working environment.

```
##make sure the old stuff has been cleaned
$ module load anaconda3/personal
$ conda remove -n 21CMMC --all -y  
$ module purge

##Create the environment
$ module load anaconda3/personal
$conda create -n 21cmmc python=3.7 gsl fftw
$source activate 21cmmc
$conda install numpy scipy click pyyaml cffi astropy h5py
$conda update pytest

##installation (+library linkage)
$cd $EPHEMERAL
$git clone https://github.com/21cmfast/21CMMC.git
$cd ./21CMMC
$INCLUDE=$CONDA_PREFIX/include DEBUG=True GSL_LIB=$CONDA_PREFIX/lib $GSL_INC=$CONDA_PREFIX/include FFTW_INC=$CONDA_PREFIX/include 
$pip install -e .
$pip install -r requirements_dev.txt

##test with 
$21cmfast --help
```

p.s. if this produces gsl library linking errors, it is because the pip cache is linked to the wrong place.

**Comment by binnietom** [comment]
Hi Steven,  
Apologies, I didn't realise that was over specific - I'm just trying to be as transparent as a can with this! Thanks for putting it in the appropriate place. The module load anaconda3/personal is equivalent to installing anaconda with python 3.

**Comment by binnietom** [comment]
...powerbox installed easily with the envs/21cmfast/bin/pip   and 21cmfast --help now runs on my desktop. 

Although I'm not sure where to begin with the workstation error - I guess a version discrepancy somewhere?

**Comment by steven-murray** [comment]
I apologise for needing `powerbox` -- I will fix that soon (it's only needed for a single function in the CLI, so it shouldn't be required globally). But it should be installed directly with pip, as you found. 

As for the workstation -- can you see what `echo $CONDA_PREFIX` is? And also what `which pip` outputs?

**Comment by binnietom** [comment]
I get:
(21cmfast) tab216@ph-jpritcha-1:~$ echo $CONDA_PREFIX
/home/tab216/anaconda3/envs/21cmfast

On my desktop (where it installed ok):
(21cmfast) tab216@dyn202-194:~$ which pip
/home/tab216/miniconda3/envs/21cmfast/bin/pip

On the workstation it looks to not be linking with the environment.
(21cmfast) tab216@ph-jpritcha-1:~$ which pip
/home/tab216/.local/bin/pip

I just tried:
(21cmfast) tab216@ph-jpritcha-1:~/21cmfast$ pip uninstall pip

$ which pip
/home/tab216/anaconda3/envs/21cmfast/bin/pip

$ INCLUDE=$CONDA_PREFIX/include LIB=$CONDA_PREFIX/lib  pip install .
-bash: /home/tab216/.local/bin/pip: No such file or directory

$ conda install pip

and now it works (after installing matplotlib and powerbox)  :)

**Comment by steven-murray** [comment]
Awesome! So it would seem that you had a weird python/pip installation which was resolved by uninstalling pip and re-installing with conda.

But the installation instructions for `21cmFAST` are correct if those things are right?

**Comment by binnietom** [comment]
- to be pernickety the there was one type-o with case so its:

# Create the environment
$ conda create -n 21cmfast python=3.7 gsl fftw
$ conda activate 21cmfast
$ conda install numpy scipy click pyyaml cffi astropy h5py matplotlib
$ pip install powerbox

# installation (+library linkage)
$ git clone https://github.com/21cmfast/21cmfast.git
$ cd 21cmfast
$ INCLUDE=$CONDA_PREFIX/include LIB=$CONDA_PREFIX/lib  pip install .

# test: 
$ 21cmfast --help

Otherwise yes.
Thanks,
Tom

**Comment by steven-murray** [comment]
Excellent. Thanks -- this will be a good future reference for people with installation issues. 

I think one useful thing I've learned from this is that gsl and fftw can be installed via `conda`. This is not currently in the documentation. I will add it.
