### ISSUE TITLE
[Feature Req.] C-only binaries

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#8]
**Is your feature request related to a problem? Please describe.**

While the Python wrapper includes a cmd-line script which is pretty general, it may be that some users don't want to muck around with python, and would rather a pure-C experience. 

**Describe the solution you'd like**

It should be possible to add a Makefile that makes binaries, similar to the original 21cmFAST. The reason that they are *not* currently in the repo is that this was based of a fork of 21cmFAST that was supposed to be run in python (while the original 21cmFAST still existed). If everything is going to be in one place, it's worth considering the needs of users who may not want to use python. 

Binaries that create the four stages (init, perturb, xHI, Tb) should be very easy to create. Scripts that do the whole thing may be a little more tricky (this is why we used python in the first place). Due to this, it is worth thinking about whether this is a useful path to go down.

**Comment by andreimesinger** [comment]
i personally as a python novice, would appreciate it if it were possible to also be run in "traditional" C mode, at least the basic binaries, without having to use python wrappers

**Comment by steven-murray** [comment]
OK. Say we want to have this functionality. Step one is to decide when we want it by: does it need to be there by v3?

Step 2 is to figure out what kinds of things we want to support via the C binaries. Do we want to create the following binaries: `init`, `perturb`, `ionize`, `spin_temp` and `brightness_temp`, along with `run_coeval` and `run_lightcone`? These would *not* be able to use the caching mechanisms that Python does, and so the loops in `run_coeval` and `run_lightcone` may look a bit different to their Python counterparts. 

Also, who's best to assign this task to?

**Comment by steven-murray** [comment]
Given the lack of input into this issue, I'm going to make it a v4 project -- I don't have the time to work on it right now. Also, there *already exists* python command-line scripts that work "almost the same" as the original C programs. They do require the user to install a python environment, but I think most people have a good amount of python experience and a working interpreter. 

I still think this will be useful in the future, but I say we shelve it for now.

**Comment by BradGreig** [comment]
@steven-murray, yeah, I think this is a sensible thing to do. In most cases it should be easy enough to have the user use the python setup.

**Comment by steven-murray** [comment]
From discussion, it seems that installation with Python now is not really hard. There is a CLI that does everything the C binary did originally (and more), and there's really no reason to use a C binary. We'll close this for now. Feel free to reopen.
