### ISSUE TITLE
[BUG] Caching doesn't work unless float precision is exact

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#80]
**Describe the bug:**

When reading from cache, if the original redshift was say 7.000001, and you ask for 7, it will recompute.

**To Reproduce:**
```
import logging
logger = logging.getLogger("21cmFAST")
logger.setLevel(logging.INFO)
p21c.run_coeval(redshift=7.00001)
p21cm.run_ceoval(redshift=7.0)
```
And notice that it doesn't say it's reading in redshift-dependent boxes.
This is annoying when the cubes are created by the lightcone scrolling at 
strange float redshifts.

**Expected behavior:**

I would expect that some tolerance in redshift should be acceptable. Maybe 10^-3?

**Comment by BradGreig** [comment]
@steven-murray yeah, setting tolerance to 10^-3 or 10^-4 for redshift should be sufficient. Rounding errors will only occur on the 6-7th decimal place anyway. Also, the redshift evolution at such a tolerance is going to be negligible.

**Comment by steven-murray** [comment]
I will try to reproduce this --- I thought I fixed it.
