### ISSUE TITLE
Make default cosmology Planck15

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#82]
It's probably a good idea to be up to date. We'll just have to be careful because this will be a breaking change. Either needs to be in v3.0.0 or delayed until v4.0.0. 

What say people? 

@JulianBMunoz I'm especially looking at you :-)

**Comment by andreimesinger** [comment]
why isn’t 2018 the default?

**Comment by JulianBMunoz** [comment]
The one file I uploaded with the transfer functions has Planck 2018 parameters. If the question is whether to change the default in the Walkers, then I say let's do it now. It'd be optimal to also have CLASS interfacing with 21cmFAST, so it outputs the transfer functions, although that might have to wait for v4. How is the progress on that @PoulinV?

**Comment by steven-murray** [comment]
Yup, Planck2018 would make sense. OK we can do it in v3.

**Comment by PoulinV** [comment]
We have a first version of an interface between 21cmFAST and CLASS, thanks to the python wrapper, i.e., py21cmmc and classy. Currently it’s going in the “wrong” direction, in the sense that it takes information from 21CMFAST to pass it to CLASS. But I think we could tweak this to make CLASS output the transfer functions before 21cmFAST makes his calculation. The catch is that the interface is actually done in 21CMMC not 21cmFAST. alternatively implementing an interface between the C codes is surely possible but requires more work, and I am not familiar enough with 21CMFAST to know how/where to do this. I am happy to chat about this on skype some time soon if you want!

**Comment by JulianBMunoz** [comment]
Hm, I see. Can we use the py21cmfast python wrapper to call classy and output the transfer functions? That should circumvent getting into the C code. I'd also be happy to chat, although I'm swamped for the next 8 days, but hopefully after that.

**Comment by PoulinV** [comment]
> Can we use the py21cmfast python wrapper to call classy and output the transfer functions? 
> 
Yes that was the idea! it is really straightforward to call CLASS from py21cmfast. let’s chat about this whenever you have some time.
