### ISSUE TITLE
[Question] Should we change the default user_params?

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#83]
At the moment, the default user params make a very small box, which is almost certainly physically inappropriate. However, it does have the advantage of being able to produce quick output for a new user firing up a trial run. 

Should we change the defaults? @JulianBMunoz ? @BradGreig ? @andreimesinger ?

**Comment by andreimesinger** [comment]
yes, i think best default runs should be something like HII_DIM = 200, DIM=800, BOX_LEN= 300

this should run reasonably fast…  if too slow, maybe cut it all by 2

**Comment by steven-murray** [comment]
Cool. I'll make it a PR soon.

**Comment by JulianBMunoz** [comment]
That's a good question, and I like Andrei's suggestion. When I did tests 300-400 Mpc was typically enough side to properly include almost all power in the relative velocities. Also, we don't need DIM to be 4 times HII_DIM, right? It might make the init part a bit slow.

**Comment by steven-murray** [comment]
Yeah we could do HII_DIM=200, BOX_LEN=300, DIM=600. Anyone who's really
trying to do something important will be specifying these properly anyway.

**Comment by BradGreig** [comment]
@steven-murray is this default size also to be used for the tests? I'm happy with the HII_DIM=200, BOX_LEN=300, DIM=600 setup as defaults, provided they are not used for the tests. The tests already take > 30 minutes to perform and with this size it'll take close to a day (with minihaloes probably even longer).

**Comment by steven-murray** [comment]
Most definitely not for the tests. In the latest PR I also streamlined the
tests a bit and they now take about 10 min!
