### ISSUE TITLE
[Feature Req.] Have some way of saving LCs to its own file

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21cmFAST#86]
**Is your feature request related to a problem? Please describe.**

It's kind of surprising to the user that Coeval and LightCone objects aren't directly written to file.
It would be good to be able to write those highest-level structures to a nice HDF5 format, and probably _not_ to cache  -- rather specifying the actual filename. 

**Describe the solution you'd like**

Basically add a write() method to Coeval and LightCone to write them to a given filename (a default filename based on input parameters should be available too). We should also provide a `read_coeval` and `read_lightcone` function (we could also attach these to the relevant classes as classmethods). 

**Describe alternatives you've considered**

We could write them to the standard cache (unless otherwise specified). This may be OK as well, as a default. It will also be a lot easier if/when we have a better database management system in place.

We could also just keep our current system, but I think this feature makes sense.

**Additional context**

One issue for this, especially for Coeval cubes, is that we're increasing disk usage quite significantly -- each of the components should already be in the cache, and then the Coeval again contains all of them. We could circumvent this by having pointers in the Coeval file that just point to the other files. However, this will break if the other files are removed...

Looking for some suggestions! @andreimesinger @qyx268 @BradGreig

**Comment by andreimesinger** [comment]
completely agree with this
