### ISSUE TITLE
The coeval class doesn't include the spin temperature box struct

### ISSUE THREAD

**Issue by BradGreig** [21cmfast/21cmFAST#90]
**Is your feature request related to a problem? Please describe.**
The existing coeval class doesn't include boxes related to the spin temperature. It is useful to be able to access the mean spin temperature etc. so I think this should be added to the coeval class.

**Comment by BradGreig** [comment]
I guess this is somewhat related to the better lightcone branch, and being able to better control the outputs of the coeval class.

**Comment by steven-murray** [comment]
Ah yes, this is true. I can add that easily.
