### ISSUE TITLE
[BUG] Inconsistent usage of the write keyword argument

### ISSUE THREAD

**Issue by BradGreig** [21cmfast/21cmFAST#92]
**Describe the bug:**
Within both the `run_coeval` and `run_lightcone` functions the `write` keyword argument does not get passed to the internal `brightness_temperature` function. This means `brightness_temperature` will default to the `config.yml` value for `write` and ignore whatever value is passed to `run_coeval` and `run_lightcone`.

**Expected behavior:**
Not sure what the best behaviour for this is. In almost all cases we definitely do not want all the intermediate data written out. However, there will be cases (like for what I was just trying to do) where we do not want anything written out at all.

**Comment by steven-murray** [comment]
Yup, that's a bug, those should be passed. 

You do bring up an interesting point though -- what if in running a coeval/lightcone, we want to pick and choose which steps are written? At the moment it's all or nothing. That's a separate issue though. Worth opening an issue for?

**Comment by BradGreig** [comment]
Yeah, I think it makes sense to make it a separate issue. Mostly because we need to come up with a sensible way to disentangling the options without making it too complicated or unwieldy for the user.

I guess for `run_coeval` it could be fairly straightforward. Could have a `write_everything` keyword, which overwrites `write` and stores everything. Then `write` could be specific to the user defined redshifts provided to `run_coeval`. However for `run_lightcone` its more complicated.

Perhaps we can use a similar approach to that of the `better_lightcone` branch and specify which boxes we want to write and which ones to ignore. However, that only deals with quantities, and not specific redshifts to output.

**Comment by steven-murray** [comment]
I've moved this particular discussion about extending the capability to #94.
